# Generated by Django 6.0 on 2026-02-16 18:12

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_shippingcountry_cart_coupon_code_cart_discount_total_and_more'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Code')),
                ('kind', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], default='percent', max_length=20, verbose_name='Type')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Valid from')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Valid to')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Usage limit')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Used count')),
                ('min_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min subtotal')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Coupon code'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='tax_rate_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Tax rate percent'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Coupon code'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Tax rate percent'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tax'),
        ),
        migrations.CreateModel(
            name='HistoricalCoupon',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Code')),
                ('kind', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], default='percent', max_length=20, verbose_name='Type')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Valid from')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Valid to')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Usage limit')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Used count')),
                ('min_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min subtotal')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Coupon',
                'verbose_name_plural': 'historical Coupons',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTaxRate',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('state', models.CharField(blank=True, default='', help_text='Optional. For example: US-CA.', max_length=80, verbose_name='State / region')),
                ('tax_type', models.CharField(choices=[('vat', 'VAT'), ('sales_tax', 'Sales tax')], default='vat', max_length=20, verbose_name='Type')),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Rate percent')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('country', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cart.shippingcountry', verbose_name='Country')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tax rate',
                'verbose_name_plural': 'historical Tax rates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(blank=True, default='', help_text='Optional. For example: US-CA.', max_length=80, verbose_name='State / region')),
                ('tax_type', models.CharField(choices=[('vat', 'VAT'), ('sales_tax', 'Sales tax')], default='vat', max_length=20, verbose_name='Type')),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Rate percent')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_rates', to='cart.shippingcountry', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Tax rate',
                'verbose_name_plural': 'Tax rates',
                'ordering': ['country__name', 'state', 'tax_type'],
                'constraints': [models.UniqueConstraint(fields=('country', 'state', 'tax_type'), name='uniq_taxrate_country_state_type')],
            },
        ),
    ]
