# Generated by Django 6.0 on 2026-02-16 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_historicalshippingcountry_iso2_and_more'),
        ('orders', '0002_coupon_historicalorder_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='kind',
            field=models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], default='percent', help_text='Percent reduces subtotal by a percentage. Fixed reduces subtotal by a currency amount.', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Coupon is valid only when cart subtotal is at least this amount.', max_digits=10, null=True, verbose_name='Min subtotal'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Optional. Maximum number of times this coupon can be used.', null=True, verbose_name='Usage limit'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='used_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the coupon has been used.', verbose_name='Used count'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(blank=True, help_text='Optional start time. Leave empty for immediate availability.', null=True, verbose_name='Valid from'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(blank=True, help_text='Optional end time. Leave empty for no expiration.', null=True, verbose_name='Valid to'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='For Percent: enter 10 for 10%. For Fixed: enter amount in store currency.', max_digits=10, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='historicalcoupon',
            name='kind',
            field=models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], default='percent', help_text='Percent reduces subtotal by a percentage. Fixed reduces subtotal by a currency amount.', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='historicalcoupon',
            name='min_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Coupon is valid only when cart subtotal is at least this amount.', max_digits=10, null=True, verbose_name='Min subtotal'),
        ),
        migrations.AlterField(
            model_name='historicalcoupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Optional. Maximum number of times this coupon can be used.', null=True, verbose_name='Usage limit'),
        ),
        migrations.AlterField(
            model_name='historicalcoupon',
            name='used_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the coupon has been used.', verbose_name='Used count'),
        ),
        migrations.AlterField(
            model_name='historicalcoupon',
            name='valid_from',
            field=models.DateTimeField(blank=True, help_text='Optional start time. Leave empty for immediate availability.', null=True, verbose_name='Valid from'),
        ),
        migrations.AlterField(
            model_name='historicalcoupon',
            name='valid_to',
            field=models.DateTimeField(blank=True, help_text='Optional end time. Leave empty for no expiration.', null=True, verbose_name='Valid to'),
        ),
        migrations.AlterField(
            model_name='historicalcoupon',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='For Percent: enter 10 for 10%. For Fixed: enter amount in store currency.', max_digits=10, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='historicaltaxrate',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Tax rate applies when checkout country matches this country (ISO2).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cart.shippingcountry', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='historicaltaxrate',
            name='rate_percent',
            field=models.DecimalField(decimal_places=2, help_text='Percent value. Example: 23 means 23%.', max_digits=6, verbose_name='Rate percent'),
        ),
        migrations.AlterField(
            model_name='historicaltaxrate',
            name='tax_type',
            field=models.CharField(choices=[('vat', 'VAT'), ('sales_tax', 'Sales tax')], default='vat', help_text='Select VAT for EU-style tax. Sales tax can be used for US-style rates.', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='country',
            field=models.ForeignKey(help_text='Tax rate applies when checkout country matches this country (ISO2).', on_delete=django.db.models.deletion.PROTECT, related_name='tax_rates', to='cart.shippingcountry', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='rate_percent',
            field=models.DecimalField(decimal_places=2, help_text='Percent value. Example: 23 means 23%.', max_digits=6, verbose_name='Rate percent'),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='tax_type',
            field=models.CharField(choices=[('vat', 'VAT'), ('sales_tax', 'Sales tax')], default='vat', help_text='Select VAT for EU-style tax. Sales tax can be used for US-style rates.', max_length=20, verbose_name='Type'),
        ),
    ]
