# Generated by Django 6.0 on 2026-02-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_taxrate_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_country',
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='shipping_postal_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Postal code'),
        ),
    ]
