# Generated by Django 6.0 on 2026-02-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_add_coupon_123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='tax_rate_percent',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='tax_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_rate_percent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_total',
        ),
    ]
