# Generated by Django 6.0 on 2026-02-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_historicalorder_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='min_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Coupon is valid only when cart total (before discounts) is at least this amount.', max_digits=10, null=True, verbose_name='Min total'),
        ),
        migrations.AlterField(
            model_name='historicalcoupon',
            name='min_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Coupon is valid only when cart total (before discounts) is at least this amount.', max_digits=10, null=True, verbose_name='Min total'),
        ),
    ]
