# Generated by Django 6.0 on 2026-03-31 07:14

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_warehouse_historicalwarehouse_historicalproductstock_and_more'),
        ('orders', '0014_add_shipped_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderline',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.warehouse', verbose_name='Source warehouse'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='catalog.warehouse', verbose_name='Source warehouse'),
        ),
        migrations.CreateModel(
            name='HistoricalOrderLineWarehouseAllocation',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order_line', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.orderline', verbose_name='Order line')),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'historical Order line warehouse allocation',
                'verbose_name_plural': 'historical Order line warehouse allocations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OrderLineWarehouseAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_allocations', to='orders.orderline', verbose_name='Order line')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Order line warehouse allocation',
                'verbose_name_plural': 'Order line warehouse allocations',
                'ordering': ['id'],
            },
        ),
    ]
