# Generated by Django 6.0 on 2026-06-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_historicalorderline_source_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='las_session_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='LAS session id'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='las_visitor_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='LAS visitor id'),
        ),
        migrations.AddField(
            model_name='order',
            name='las_session_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='LAS session id'),
        ),
        migrations.AddField(
            model_name='order',
            name='las_visitor_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='LAS visitor id'),
        ),
    ]
