# Generated by Django 6.0 on 2026-01-22 10:23

import apps.web.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BottomBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle bottom bar visibility.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Bottom bar',
                'verbose_name_plural': 'Bottom bar',
            },
        ),
        migrations.CreateModel(
            name='CustomCSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_css', models.TextField(blank=True, verbose_name='custom CSS')),
                ('custom_css_active', models.BooleanField(default=False, help_text='When enabled, custom CSS is applied to the public site.', verbose_name='custom CSS active')),
            ],
            options={
                'verbose_name': 'Custom CSS',
                'verbose_name_plural': 'Custom CSS',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('content_type', models.CharField(choices=[('standard', 'Standard'), ('custom', 'Custom')], default='standard', max_length=20, verbose_name='Content type')),
                ('custom_html', models.TextField(blank=True, default='', verbose_name='Custom HTML')),
                ('custom_css', models.TextField(blank=True, default='', help_text='Optional CSS styles for the custom HTML. These styles apply only to this section.', verbose_name='Custom CSS')),
                ('custom_js', models.TextField(blank=True, default='', help_text='Optional JavaScript for the custom section. Only available for staff users.', verbose_name='Custom JavaScript')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle footer visibility.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_name', models.CharField(blank=True, default='', help_text='Name of your store, used in page titles and SEO.', max_length=200, verbose_name='Store name')),
                ('site_url', models.URLField(blank=True, default='', help_text='Main URL of the site (e.g. https://example.com).', verbose_name='Site URL')),
                ('description', models.TextField(blank=True, default='', help_text='Description used in meta tags for SEO.', verbose_name='Site description')),
                ('keywords', models.CharField(blank=True, default='', help_text='Comma-separated keywords for search engines.', max_length=500, verbose_name='SEO keywords')),
                ('default_image', models.ImageField(blank=True, help_text='Image used for social media sharing and search engine previews (og:image).', null=True, upload_to='site/', verbose_name='Default image')),
                ('currency', models.CharField(choices=[('PLN', 'PLN (zł)'), ('EUR', 'EUR (€)'), ('USD', 'USD ($)')], default='PLN', help_text='Currency symbol displayed on prices. No conversion is performed - this is display only.', max_length=3, verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='TopBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Internal name for identification.', max_length=120, verbose_name='Name')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('content_type', models.CharField(choices=[('standard', 'Standard'), ('custom', 'Custom')], default='standard', max_length=20, verbose_name='Content type')),
                ('background_color', models.CharField(default='#1A56DB', help_text='Hex code (e.g. #1A56DB) to use as background.', max_length=50, verbose_name='Background color')),
                ('text', models.CharField(help_text='Message displayed in the top bar.', max_length=240, verbose_name='Text')),
                ('link_label', models.CharField(blank=True, default='', help_text='Optional call-to-action button label.', max_length=60, verbose_name='Link label')),
                ('link_url', models.URLField(blank=True, default='', help_text='URL for the call-to-action. If set without label, the text becomes a link.', max_length=500, verbose_name='Link URL')),
                ('custom_html', models.TextField(blank=True, default='', verbose_name='Custom HTML')),
                ('custom_css', models.TextField(blank=True, default='', help_text='Optional CSS styles for the custom HTML. These styles apply only to this section.', verbose_name='Custom CSS')),
                ('custom_js', models.TextField(blank=True, default='', help_text='Optional JavaScript for the custom section. Only available for staff users.', verbose_name='Custom JavaScript')),
                ('is_active', models.BooleanField(default=True, help_text='Only active top bars can be displayed.', verbose_name='Active')),
                ('available_from', models.DateTimeField(blank=True, help_text='Start date (leave empty for immediate display).', null=True, verbose_name='Available from')),
                ('available_to', models.DateTimeField(blank=True, help_text='End date (leave empty for no end date).', null=True, verbose_name='Available to')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = higher priority.', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Top bar',
                'verbose_name_plural': 'Top bar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BottomBarLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120, verbose_name='Label')),
                ('url', models.CharField(max_length=500, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('bottom_bar', models.ForeignKey(default=apps.web.models.BottomBar.get_settings, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='web.bottombar', verbose_name='Bottom bar')),
            ],
            options={
                'verbose_name': 'Bottom bar link',
                'verbose_name_plural': 'Bottom bar links',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Section name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('footer', models.ForeignKey(default=apps.web.models.Footer.get_settings, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='web.footer', verbose_name='Footer')),
            ],
            options={
                'verbose_name': 'Footer section',
                'verbose_name_plural': 'Footer sections',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterSectionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120, verbose_name='Label')),
                ('url', models.CharField(max_length=500, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='web.footersection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Footer section link',
                'verbose_name_plural': 'Footer section links',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterSocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('tiktok', 'TikTok')], max_length=20, verbose_name='Platform')),
                ('label', models.CharField(blank=True, default='', help_text='Optional label displayed next to the icon.', max_length=60, verbose_name='Display label')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('footer', models.ForeignKey(default=apps.web.models.Footer.get_settings, on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='web.footer', verbose_name='Footer')),
            ],
            options={
                'verbose_name': 'Social media link',
                'verbose_name_plural': 'Social media links',
                'ordering': ['order', 'id'],
            },
        ),
    ]
