# Generated by Django 6.0 on 2026-01-28 00:00

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_category_sort_order_icon"),
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Navbar",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("singleton_key", models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ("mode", models.CharField(
                    choices=[("standard", "Standard (categories alphabetically)"), ("custom", "Custom navigation")],
                    default="standard",
                    help_text="Standard: shows categories alphabetically. Custom: shows manually configured items.",
                    max_length=20,
                    verbose_name="Navigation mode",
                )),
            ],
            options={
                "verbose_name": "Navigation bar",
                "verbose_name_plural": "Navigation bar",
            },
        ),
        migrations.CreateModel(
            name="NavbarItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("item_type", models.CharField(
                    choices=[("category", "Category"), ("custom_link", "Custom link"), ("separator", "Separator")],
                    default="category",
                    max_length=20,
                    verbose_name="Item type",
                )),
                ("label", models.CharField(
                    blank=True,
                    default="",
                    help_text="Display label for custom links.",
                    max_length=120,
                    verbose_name="Label",
                )),
                ("url", models.CharField(
                    blank=True,
                    default="",
                    help_text="URL for custom links. Can be relative (/page) or absolute (https://...).",
                    max_length=500,
                    verbose_name="URL",
                )),
                ("open_in_new_tab", models.BooleanField(
                    default=False,
                    help_text="If enabled, the link opens in a new browser tab.",
                    verbose_name="Open in new tab",
                )),
                ("label_color", colorfield.fields.ColorField(
                    blank=True,
                    default="",
                    help_text="Optional color for the label text.",
                    image_field=None,
                    max_length=25,
                    samples=None,
                    verbose_name="Label color",
                )),
                ("icon", models.CharField(
                    blank=True,
                    default="",
                    help_text="Optional icon class name (e.g., 'star', 'fire', 'tag').",
                    max_length=50,
                    verbose_name="Icon",
                )),
                ("order", models.PositiveIntegerField(
                    default=0,
                    help_text="Lower number = appears first.",
                    verbose_name="Order",
                )),
                ("is_active", models.BooleanField(
                    default=True,
                    help_text="Inactive items are not displayed.",
                    verbose_name="Active",
                )),
                ("category", models.ForeignKey(
                    blank=True,
                    help_text="Select a category to display (only for category type).",
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="navbar_items",
                    to="catalog.category",
                    verbose_name="Category",
                )),
                ("navbar", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="items",
                    to="web.navbar",
                    verbose_name="Navbar",
                )),
            ],
            options={
                "verbose_name": "Navbar item",
                "verbose_name_plural": "Navbar items",
                "ordering": ["order", "id"],
            },
        ),
    ]
