# Generated by Django 6.0 on 2026-02-04 08:09

import autoslug.fields
import django.db.models.deletion
import django_ckeditor_5.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_navbaritem_navbar_historicalbottombar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique=True)),
                ('meta_title', models.CharField(blank=True, default='', max_length=200, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, default='', verbose_name='Meta description')),
                ('is_active', models.BooleanField(default=True, help_text='Controls page visibility.', verbose_name='Visible')),
                ('exclude_from_sitemap', models.BooleanField(default=False, verbose_name='Exclude from sitemap')),
                ('seo_noindex', models.BooleanField(default=False, help_text='Adds a noindex directive to search engines.', verbose_name='SEO noindex')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Dynamic page',
                'verbose_name_plural': 'Dynamic pages',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='footersectionlink',
            name='link_type',
            field=models.CharField(choices=[('custom_url', 'Custom URL'), ('dynamic_page', 'Dynamic page')], default='custom_url', max_length=30, verbose_name='Link type'),
        ),
        migrations.AddField(
            model_name='historicalfootersectionlink',
            name='link_type',
            field=models.CharField(choices=[('custom_url', 'Custom URL'), ('dynamic_page', 'Dynamic page')], default='custom_url', max_length=30, verbose_name='Link type'),
        ),
        migrations.AlterField(
            model_name='footersectionlink',
            name='label',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='footersectionlink',
            name='url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='historicalfootersectionlink',
            name='label',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='historicalfootersectionlink',
            name='url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='historicalnavbaritem',
            name='item_type',
            field=models.CharField(choices=[('category', 'Category'), ('custom_link', 'Custom link'), ('dynamic_page', 'Dynamic page'), ('separator', 'Separator')], default='category', max_length=20, verbose_name='Item type'),
        ),
        migrations.AlterField(
            model_name='navbaritem',
            name='item_type',
            field=models.CharField(choices=[('category', 'Category'), ('custom_link', 'Custom link'), ('dynamic_page', 'Dynamic page'), ('separator', 'Separator')], default='category', max_length=20, verbose_name='Item type'),
        ),
        migrations.AddField(
            model_name='footersectionlink',
            name='dynamic_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_links', to='web.dynamicpage', verbose_name='Dynamic page'),
        ),
        migrations.AddField(
            model_name='historicalfootersectionlink',
            name='dynamic_page',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='web.dynamicpage', verbose_name='Dynamic page'),
        ),
        migrations.AddField(
            model_name='historicalnavbaritem',
            name='dynamic_page',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Select a dynamic page to display.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='web.dynamicpage', verbose_name='Dynamic page'),
        ),
        migrations.AddField(
            model_name='navbaritem',
            name='dynamic_page',
            field=models.ForeignKey(blank=True, help_text='Select a dynamic page to display.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navbar_items', to='web.dynamicpage', verbose_name='Dynamic page'),
        ),
        migrations.CreateModel(
            name='HistoricalDynamicPage',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='title')),
                ('meta_title', models.CharField(blank=True, default='', max_length=200, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, default='', verbose_name='Meta description')),
                ('is_active', models.BooleanField(default=True, help_text='Controls page visibility.', verbose_name='Visible')),
                ('exclude_from_sitemap', models.BooleanField(default=False, verbose_name='Exclude from sitemap')),
                ('seo_noindex', models.BooleanField(default=False, help_text='Adds a noindex directive to search engines.', verbose_name='SEO noindex')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Content')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Dynamic page',
                'verbose_name_plural': 'historical Dynamic pages',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
