# Generated by Django 6.0 on 2026-02-05 11:38

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_historicaldynamicpage_title_to_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicpage',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='historicaldynamicpage',
            name='name',
            field=models.CharField(help_text='Internal name for identification', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicaldynamicpage',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='name'),
        ),
    ]
