# Generated by Django 6.0 on 2026-02-09 08:41

import apps.media.storage
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_dynamicpage_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smtp_host', models.CharField(default='smtp.sendgrid.net', max_length=255, verbose_name='SMTP host')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='SMTP port')),
                ('smtp_username', models.CharField(blank=True, default='apikey', max_length=255, verbose_name='SMTP username')),
                ('smtp_password_encrypted', models.TextField(blank=True, default='', help_text='Stored encrypted. Managed via the admin form.', verbose_name='SMTP password (encrypted)')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('smtp_use_ssl', models.BooleanField(default=False, verbose_name='Use SSL')),
                ('smtp_default_from_email', models.EmailField(default='noreply@ampliapps.com', max_length=254, verbose_name='Default from email')),
                ('smtp_timeout', models.PositiveIntegerField(default=30, verbose_name='SMTP timeout (seconds)')),
                ('smtp_enabled', models.BooleanField(default=False, help_text='When disabled, emails are printed to the console.', verbose_name='SMTP enabled')),
                ('recaptcha_public_key', models.CharField(blank=True, default='', max_length=255, verbose_name='reCAPTCHA site key')),
                ('recaptcha_private_key_encrypted', models.TextField(blank=True, default='', help_text='Stored encrypted. Managed via the admin form.', verbose_name='reCAPTCHA secret key (encrypted)')),
                ('recaptcha_enabled', models.BooleanField(default=False, help_text='Enable Google reCAPTCHA on the registration form.', verbose_name='reCAPTCHA enabled')),
            ],
            options={
                'verbose_name': 'System settings',
                'verbose_name_plural': 'System settings',
            },
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='logo',
            field=models.TextField(blank=True, help_text='Logo displayed in emails and branding. Defaults to the built-in SVG.', max_length=100, verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo displayed in emails and branding. Defaults to the built-in SVG.', storage=apps.media.storage.DynamicMediaStorage(), upload_to='site/', verbose_name='Logo'),
        ),
        migrations.CreateModel(
            name='HistoricalSystemSettings',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('smtp_host', models.CharField(default='smtp.sendgrid.net', max_length=255, verbose_name='SMTP host')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='SMTP port')),
                ('smtp_username', models.CharField(blank=True, default='apikey', max_length=255, verbose_name='SMTP username')),
                ('smtp_password_encrypted', models.TextField(blank=True, default='', help_text='Stored encrypted. Managed via the admin form.', verbose_name='SMTP password (encrypted)')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('smtp_use_ssl', models.BooleanField(default=False, verbose_name='Use SSL')),
                ('smtp_default_from_email', models.EmailField(default='noreply@ampliapps.com', max_length=254, verbose_name='Default from email')),
                ('smtp_timeout', models.PositiveIntegerField(default=30, verbose_name='SMTP timeout (seconds)')),
                ('smtp_enabled', models.BooleanField(default=False, help_text='When disabled, emails are printed to the console.', verbose_name='SMTP enabled')),
                ('recaptcha_public_key', models.CharField(blank=True, default='', max_length=255, verbose_name='reCAPTCHA site key')),
                ('recaptcha_private_key_encrypted', models.TextField(blank=True, default='', help_text='Stored encrypted. Managed via the admin form.', verbose_name='reCAPTCHA secret key (encrypted)')),
                ('recaptcha_enabled', models.BooleanField(default=False, help_text='Enable Google reCAPTCHA on the registration form.', verbose_name='reCAPTCHA enabled')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical System settings',
                'verbose_name_plural': 'historical System settings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
