# Generated by Django 6.0 on 2026-02-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_systemsettings_historicalsitesettings_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsystemsettings',
            name='recaptcha_enabled',
        ),
        migrations.RemoveField(
            model_name='historicalsystemsettings',
            name='recaptcha_private_key_encrypted',
        ),
        migrations.RemoveField(
            model_name='historicalsystemsettings',
            name='recaptcha_public_key',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='recaptcha_enabled',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='recaptcha_private_key_encrypted',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='recaptcha_public_key',
        ),
        migrations.AddField(
            model_name='historicalsystemsettings',
            name='turnstile_enabled',
            field=models.BooleanField(default=False, help_text='Enable Cloudflare Turnstile on registration and login forms.', verbose_name='Turnstile enabled'),
        ),
        migrations.AddField(
            model_name='historicalsystemsettings',
            name='turnstile_secret_key_encrypted',
            field=models.TextField(blank=True, default='', help_text='Stored encrypted. Managed via the admin form.', verbose_name='Turnstile secret key (encrypted)'),
        ),
        migrations.AddField(
            model_name='historicalsystemsettings',
            name='turnstile_site_key',
            field=models.CharField(blank=True, default='', help_text='Cloudflare Turnstile site key (visible in browser).', max_length=255, verbose_name='Turnstile site key'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='turnstile_enabled',
            field=models.BooleanField(default=False, help_text='Enable Cloudflare Turnstile on registration and login forms.', verbose_name='Turnstile enabled'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='turnstile_secret_key_encrypted',
            field=models.TextField(blank=True, default='', help_text='Stored encrypted. Managed via the admin form.', verbose_name='Turnstile secret key (encrypted)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='turnstile_site_key',
            field=models.CharField(blank=True, default='', help_text='Cloudflare Turnstile site key (visible in browser).', max_length=255, verbose_name='Turnstile site key'),
        ),
    ]
