# Generated by Django 6.0 on 2026-02-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_replace_recaptcha_with_turnstile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsystemsettings',
            name='smtp_default_from_email',
            field=models.EmailField(blank=True, default='', help_text='The sender email address that recipients will see (e.g. noreply@yourcompany.com).', max_length=254, verbose_name='Default from email'),
        ),
        migrations.AlterField(
            model_name='historicalsystemsettings',
            name='smtp_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, emails are sent via the configured mail server. When disabled, emails are not delivered.', verbose_name='SMTP enabled'),
        ),
        migrations.AlterField(
            model_name='historicalsystemsettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='', help_text="The address of your email provider's mail server (e.g. smtp.sendgrid.net, smtp.gmail.com).", max_length=255, verbose_name='SMTP host'),
        ),
        migrations.AlterField(
            model_name='historicalsystemsettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587, help_text='Port number for the mail server. Common values: 587 (STARTTLS) or 465 (SSL).', verbose_name='SMTP port'),
        ),
        migrations.AlterField(
            model_name='historicalsystemsettings',
            name='smtp_timeout',
            field=models.PositiveIntegerField(default=30, help_text='How long to wait (in seconds) for the mail server to respond before giving up. Default is 30 seconds.', verbose_name='SMTP timeout (seconds)'),
        ),
        migrations.AlterField(
            model_name='historicalsystemsettings',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False, help_text='Encrypts the connection using SSL (typically used with port 465). Do not enable both TLS and SSL at the same time.', verbose_name='Use SSL'),
        ),
        migrations.AlterField(
            model_name='historicalsystemsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, help_text='Encrypts the connection to the mail server using TLS (recommended for port 587). Do not enable both TLS and SSL at the same time.', verbose_name='Use TLS'),
        ),
        migrations.AlterField(
            model_name='historicalsystemsettings',
            name='smtp_username',
            field=models.CharField(blank=True, default='', help_text='The login username for your email provider.', max_length=255, verbose_name='SMTP username'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='smtp_default_from_email',
            field=models.EmailField(blank=True, default='', help_text='The sender email address that recipients will see (e.g. noreply@yourcompany.com).', max_length=254, verbose_name='Default from email'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='smtp_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, emails are sent via the configured mail server. When disabled, emails are not delivered.', verbose_name='SMTP enabled'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='', help_text="The address of your email provider's mail server (e.g. smtp.sendgrid.net, smtp.gmail.com).", max_length=255, verbose_name='SMTP host'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587, help_text='Port number for the mail server. Common values: 587 (STARTTLS) or 465 (SSL).', verbose_name='SMTP port'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='smtp_timeout',
            field=models.PositiveIntegerField(default=30, help_text='How long to wait (in seconds) for the mail server to respond before giving up. Default is 30 seconds.', verbose_name='SMTP timeout (seconds)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False, help_text='Encrypts the connection using SSL (typically used with port 465). Do not enable both TLS and SSL at the same time.', verbose_name='Use SSL'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, help_text='Encrypts the connection to the mail server using TLS (recommended for port 587). Do not enable both TLS and SSL at the same time.', verbose_name='Use TLS'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='smtp_username',
            field=models.CharField(blank=True, default='', help_text='The login username for your email provider.', max_length=255, verbose_name='SMTP username'),
        ),
    ]
