# Generated by Django 6.0 on 2026-02-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0012_remove_sendgrid_defaults_from_system_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_test_recipient_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Default recipient used for SMTP test emails sent from the admin panel.",
                max_length=254,
                verbose_name="Test recipient email",
            ),
        ),
        migrations.AddField(
            model_name="historicalsystemsettings",
            name="smtp_test_recipient_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Default recipient used for SMTP test emails sent from the admin panel.",
                max_length=254,
                verbose_name="Test recipient email",
            ),
        ),
    ]
