# Generated by Django 6.0 on 2026-02-10 09:09

import apps.media.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_systemsettings_smtp_test_recipient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsitesettings',
            name='logo',
            field=models.TextField(blank=True, help_text='Logo displayed in the store, emails, and branding. Supports SVG, PNG, JPG.', max_length=100, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.FileField(blank=True, help_text='Logo displayed in the store, emails, and branding. Supports SVG, PNG, JPG.', storage=apps.media.storage.DynamicMediaStorage(), upload_to='site/', verbose_name='Logo'),
        ),
    ]
