# Generated by Django 6.0 on 2026-02-12 13:59

import apps.media.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_sitesettings_currency_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsitesettings',
            name='currency',
            field=models.CharField(choices=[('PLN', 'PLN (zł)'), ('EUR', 'EUR (€)'), ('USD', 'USD ($)')], default='USD', help_text='Currency symbol displayed on prices. No conversion is performed - this is display only.', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='historicalsitesettings',
            name='logo',
            field=models.TextField(blank=True, help_text='Logo displayed in the store, emails, and branding. Supports PNG, JPG.', max_length=100, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.FileField(blank=True, help_text='Logo displayed in the store, emails, and branding. Supports PNG, JPG.', storage=apps.media.storage.DynamicMediaStorage(), upload_to='site/', verbose_name='Logo'),
        ),
    ]
