# Generated by Django 6.0 on 2026-02-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_sitesettings_vat_rate_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsitesettings',
            name='vat_rate_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Store-wide VAT rate (percent). Example: 23 means 23%.', max_digits=6, verbose_name='VAT rate percent'),
        ),
    ]
