# Generated by Django 6.0 on 2026-02-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_historicalsitesettings_vat_rate_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsitesettings',
            name='vat_rate_percent',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='vat_rate_percent',
        ),
    ]
