# Generated by Django 6.0 on 2026-02-17 15:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_historical_css_hook_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalbottombar',
            name='css_hook',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalbottombarlink',
            name='css_hook',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicaldynamicpage',
            name='css_hook',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalfooter',
            name='css_hook',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalfootersection',
            name='css_hook',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalfootersectionlink',
            name='css_hook',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalfootersocialmedia',
            name='css_hook',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalnavbar',
            name='css_hook',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalnavbaritem',
            name='css_hook',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicaltopbar',
            name='css_hook',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
