# Generated by Django 6.0 on 2026-03-31 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportProcess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_finished", models.DateTimeField(blank=True, null=True)),
                ("object_type", models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ImportProcessDetails",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_external_id", models.CharField(max_length=500)),
                (
                    "import_process",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="details", to="connector.importprocess"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Connector",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_type", models.CharField(max_length=100)),
                ("internal_id", models.CharField(max_length=500)),
                ("external_id", models.CharField(db_index=True, max_length=500)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("last_modification", models.DateTimeField(auto_now=True)),
                (
                    "import_process",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="connectors", to="connector.importprocess"),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["object_type", "internal_id"], name="connector_o_internal_1a07ed_idx")],
                "unique_together": {("object_type", "external_id")},
            },
        ),
    ]