# Generated by Django 6.0 on 2026-07-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='connector',
            new_name='connector_c_object__4cf1e1_idx',
            old_name='connector_o_internal_1a07ed_idx',
        ),
    ]
