# Generated by Django 6.0 on 2026-01-22 10:21

import apps.homepage.models
import apps.media.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Internal name for identification', max_length=255, verbose_name='Name')),
                ('image', models.ImageField(help_text='Desktop banner. Recommended size: 1920x400 pixels. Displayed on screens wider than 768px.', storage=apps.media.storage.DynamicMediaStorage(), upload_to=apps.homepage.models._get_banner_filename, verbose_name='Image')),
                ('mobile_image', models.ImageField(blank=True, help_text='Optional mobile-optimized banner. Recommended ratio 2:1 (wide) or 1:1 (square). Displayed on screens ≤768px wide. If not provided, the desktop image will be used.', null=True, storage=apps.media.storage.DynamicMediaStorage(), upload_to=apps.homepage.models._get_banner_filename, verbose_name='Mobile Image')),
                ('url', models.URLField(blank=True, default='', help_text='URL to redirect when the banner is clicked', max_length=500, verbose_name='Target URL')),
                ('is_active', models.BooleanField(default=True, help_text='Only active banners will be displayed', verbose_name='Active')),
                ('available_from', models.DateTimeField(blank=True, help_text='Start date and time for banner display (leave empty for immediate display)', null=True, verbose_name='Available from')),
                ('available_to', models.DateTimeField(blank=True, help_text='End date and time for banner display (leave empty for no end date)', null=True, verbose_name='Available to')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower number = higher priority)', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_type', models.CharField(choices=[('product_list', 'Product list'), ('banner_section', 'Banner section'), ('custom_section', 'Custom section')], default='product_list', max_length=50, verbose_name='Section type')),
                ('name', models.CharField(blank=True, default='', help_text='Internal name for identification', max_length=255, verbose_name='Name')),
                ('title', models.CharField(blank=True, default='', help_text='Optional title displayed above the section.', max_length=120, verbose_name='Title')),
                ('custom_html', models.TextField(blank=True, default='', verbose_name='Custom HTML')),
                ('custom_css', models.TextField(blank=True, default='', help_text='Optional styles for the custom section. Only layout and typography styles are allowed.', verbose_name='Custom CSS')),
                ('custom_js', models.TextField(blank=True, default='', help_text='Optional JavaScript for the custom section. Only available for staff users.', verbose_name='Custom JavaScript')),
                ('is_enabled', models.BooleanField(default=True, help_text='Only enabled sections will be displayed.', verbose_name='Active')),
                ('available_from', models.DateTimeField(blank=True, help_text='Start date and time for section display (leave empty for immediate display).', null=True, verbose_name='Available from')),
                ('available_to', models.DateTimeField(blank=True, help_text='End date and time for section display (leave empty for no end date).', null=True, verbose_name='Available to')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower number = higher priority).', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomepageSectionBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Internal name for identification', max_length=255, verbose_name='Name')),
                ('image', models.ImageField(storage=apps.media.storage.DynamicMediaStorage(), upload_to=apps.homepage.models._get_section_banner_filename, verbose_name='Image')),
                ('url', models.URLField(blank=True, default='', help_text='URL to redirect when the banner is clicked', max_length=500, verbose_name='Target URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower number = higher priority).', verbose_name='Order')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_banners', to='homepage.homepagesection')),
            ],
            options={
                'verbose_name': 'Section banner',
                'verbose_name_plural': 'Section banners',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomepageSectionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower number = higher priority).', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_section_products', to='catalog.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_products', to='homepage.homepagesection')),
            ],
            options={
                'verbose_name': 'Homepage section product',
                'verbose_name_plural': 'Homepage section products',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='homepage_sections', through='homepage.HomepageSectionProduct', to='catalog.product'),
        ),
        migrations.AddConstraint(
            model_name='homepagesectionproduct',
            constraint=models.UniqueConstraint(fields=('section', 'product'), name='uniq_homepage_section_product'),
        ),
    ]
