# Generated by Django 6.0 on 2026-01-22 12:03

import apps.homepage.models
import apps.media.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Desktop banner. Recommended size: 1920x400 pixels. Displayed on screens wider than 768px. Images scale to fill the width; the height adjusts automatically to maintain proportions (limited to 600px on desktop).', storage=apps.media.storage.DynamicMediaStorage(), upload_to=apps.homepage.models._get_banner_filename, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Optional mobile-optimized banner. Recommended size: 1080x540 pixels. Displayed on screens ≤768px. Images scale to fill the width; the height adjusts automatically to maintain proportions. If not provided, the desktop image will be used.', null=True, storage=apps.media.storage.DynamicMediaStorage(), upload_to=apps.homepage.models._get_banner_filename, verbose_name='Mobile Image'),
        ),
    ]
