# Generated by Django 6.0 on 2026-01-28 00:00

import uuid

import apps.media.storage
import django.db.models.deletion
from django.db import migrations, models


def _get_storefront_image_filename(instance, filename):
    """Use random filename to prevent overwriting existing files & to fix caching issues."""
    return f"storefront/{uuid.uuid4()}.{filename.split('.')[-1]}"


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0002_alter_banner_image_alter_banner_mobile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorefrontHeroSection",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(
                    default="Don't miss out on exclusive deals.",
                    help_text="Main headline displayed on the left side.",
                    max_length=255,
                    verbose_name="Title",
                )),
                ("subtitle", models.TextField(
                    default="Unlock even more exclusive member deals when you become a Plus or Diamond member.",
                    help_text="Description text below the title.",
                    verbose_name="Subtitle",
                )),
                ("primary_button_text", models.CharField(
                    default="Shop Now",
                    help_text="Text displayed on the primary CTA button.",
                    max_length=100,
                    verbose_name="Primary button text",
                )),
                ("primary_button_url", models.CharField(
                    blank=True,
                    default="#",
                    help_text="Use '#', relative path (e.g., /shop/), or full URL.",
                    max_length=500,
                    verbose_name="Primary button URL",
                )),
                ("secondary_button_text", models.CharField(
                    default="Learn more",
                    help_text="Text displayed on the secondary outline button.",
                    max_length=100,
                    verbose_name="Secondary button text",
                )),
                ("secondary_button_url", models.CharField(
                    blank=True,
                    default="#",
                    help_text="Use '#', relative path (e.g., /about/), or full URL.",
                    max_length=500,
                    verbose_name="Secondary button URL",
                )),
                ("primary_button_open_in_new_tab", models.BooleanField(
                    default=False,
                    help_text="If enabled, the primary button link opens in a new browser tab.",
                    verbose_name="Primary button opens in new tab",
                )),
                ("secondary_button_open_in_new_tab", models.BooleanField(
                    default=False,
                    help_text="If enabled, the secondary button link opens in a new browser tab.",
                    verbose_name="Secondary button opens in new tab",
                )),
                ("is_active", models.BooleanField(
                    default=True,
                    help_text="Only active sections will be displayed.",
                    verbose_name="Active",
                )),
                ("available_from", models.DateTimeField(
                    blank=True,
                    help_text="Start date and time for display (leave empty for immediate display).",
                    null=True,
                    verbose_name="Available from",
                )),
                ("available_to", models.DateTimeField(
                    blank=True,
                    help_text="End date and time for display (leave empty for no end date).",
                    null=True,
                    verbose_name="Available to",
                )),
            ],
            options={
                "verbose_name": "Storefront Hero Section",
                "verbose_name_plural": "Storefront Hero Sections",
            },
        ),
        migrations.CreateModel(
            name="StorefrontCategoryBox",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(
                    help_text="Box title (e.g., 'Top categories', 'Shop consumer electronics'). Keep it short (2–4 words).",
                    max_length=255,
                    verbose_name="Title",
                )),
                ("shop_link_text", models.CharField(
                    default="Shop now",
                    help_text="Text for the link at the bottom (e.g., 'Shop now', 'Browse all').",
                    max_length=100,
                    verbose_name="Shop link text",
                )),
                ("shop_link_url", models.CharField(
                    blank=True,
                    default="#",
                    help_text="Use '#', relative path (e.g., /categories/), or full URL.",
                    max_length=500,
                    verbose_name="Shop link URL",
                )),
                ("shop_link_open_in_new_tab", models.BooleanField(
                    default=False,
                    help_text="If enabled, the shop link opens in a new browser tab.",
                    verbose_name="Shop link opens in new tab",
                )),
                ("order", models.PositiveIntegerField(
                    default=0,
                    help_text="Display order (lower number = higher priority).",
                    verbose_name="Order",
                )),
                ("section", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="category_boxes",
                    to="homepage.storefrontherosection",
                )),
            ],
            options={
                "verbose_name": "Category Box",
                "verbose_name_plural": "Category Boxes",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="StorefrontCategoryItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(
                    help_text="Item name (e.g., 'Computers', 'Gaming').",
                    max_length=100,
                    verbose_name="Name",
                )),
                ("image", models.ImageField(
                    help_text="Item image. Supported formats: SVG (recommended), PNG, JPG, WEBP. SVG works best for crisp icons. Example file: category_computers.svg.",
                    storage=apps.media.storage.DynamicMediaStorage(),
                    upload_to="storefront/",
                    verbose_name="Image",
                )),
                ("url", models.CharField(
                    blank=True,
                    default="#",
                    help_text="Use '#', relative path (e.g., /c/computers/), or full URL.",
                    max_length=500,
                    verbose_name="URL",
                )),
                ("open_in_new_tab", models.BooleanField(
                    default=False,
                    help_text="If enabled, the item link opens in a new browser tab.",
                    verbose_name="Open in new tab",
                )),
                ("order", models.PositiveIntegerField(
                    default=0,
                    help_text="Display order (lower number = higher priority).",
                    verbose_name="Order",
                )),
                ("category_box", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="items",
                    to="homepage.storefrontcategorybox",
                )),
            ],
            options={
                "verbose_name": "Category Item",
                "verbose_name_plural": "Category Items",
                "ordering": ["order", "id"],
            },
        ),
    ]
