# Generated by Django 6.0 on 2026-01-28 18:12

import apps.homepage.models
import apps.media.storage
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_storefrontcategoryitem_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhomepagesection',
            name='primary_button_open_in_new_tab',
            field=models.BooleanField(default=False, help_text='If enabled, the primary button link opens in a new browser tab.', verbose_name='Primary button opens in new tab'),
        ),
        migrations.AddField(
            model_name='historicalhomepagesection',
            name='primary_button_text',
            field=models.CharField(blank=True, default='', help_text='Text displayed on the primary CTA button.', max_length=100, verbose_name='Primary button text'),
        ),
        migrations.AddField(
            model_name='historicalhomepagesection',
            name='primary_button_url',
            field=models.CharField(blank=True, default='#', help_text="Use '#', relative path (e.g., /shop/), or full URL.", max_length=500, verbose_name='Primary button URL'),
        ),
        migrations.AddField(
            model_name='historicalhomepagesection',
            name='secondary_button_open_in_new_tab',
            field=models.BooleanField(default=False, help_text='If enabled, the secondary button link opens in a new browser tab.', verbose_name='Secondary button opens in new tab'),
        ),
        migrations.AddField(
            model_name='historicalhomepagesection',
            name='secondary_button_text',
            field=models.CharField(blank=True, default='', help_text='Text displayed on the secondary outline button.', max_length=100, verbose_name='Secondary button text'),
        ),
        migrations.AddField(
            model_name='historicalhomepagesection',
            name='secondary_button_url',
            field=models.CharField(blank=True, default='#', help_text="Use '#', relative path (e.g., /about/), or full URL.", max_length=500, verbose_name='Secondary button URL'),
        ),
        migrations.AddField(
            model_name='historicalhomepagesection',
            name='subtitle',
            field=models.TextField(blank=True, default='', help_text='Description text below the title (for Storefront Hero).', verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='primary_button_open_in_new_tab',
            field=models.BooleanField(default=False, help_text='If enabled, the primary button link opens in a new browser tab.', verbose_name='Primary button opens in new tab'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='primary_button_text',
            field=models.CharField(blank=True, default='', help_text='Text displayed on the primary CTA button.', max_length=100, verbose_name='Primary button text'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='primary_button_url',
            field=models.CharField(blank=True, default='#', help_text="Use '#', relative path (e.g., /shop/), or full URL.", max_length=500, verbose_name='Primary button URL'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='secondary_button_open_in_new_tab',
            field=models.BooleanField(default=False, help_text='If enabled, the secondary button link opens in a new browser tab.', verbose_name='Secondary button opens in new tab'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='secondary_button_text',
            field=models.CharField(blank=True, default='', help_text='Text displayed on the secondary outline button.', max_length=100, verbose_name='Secondary button text'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='secondary_button_url',
            field=models.CharField(blank=True, default='#', help_text="Use '#', relative path (e.g., /about/), or full URL.", max_length=500, verbose_name='Secondary button URL'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='subtitle',
            field=models.TextField(blank=True, default='', help_text='Description text below the title (for Storefront Hero).', verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='historicalhomepagesection',
            name='section_type',
            field=models.CharField(choices=[('product_list', 'Product list'), ('banner_section', 'Banner section'), ('custom_section', 'Custom section'), ('storefront_hero', 'Storefront hero')], default='product_list', max_length=50, verbose_name='Section type'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(choices=[('product_list', 'Product list'), ('banner_section', 'Banner section'), ('custom_section', 'Custom section'), ('storefront_hero', 'Storefront hero')], default='product_list', max_length=50, verbose_name='Section type'),
        ),
        migrations.CreateModel(
            name='HistoricalHomepageSectionCategoryBox',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('title', models.CharField(help_text="Box title (e.g., 'Top categories', 'Shop consumer electronics'). Keep it short (2–4 words).", max_length=255, verbose_name='Title')),
                ('shop_link_text', models.CharField(default='Shop now', help_text="Text for the link at the bottom (e.g., 'Shop now', 'Browse all').", max_length=100, verbose_name='Shop link text')),
                ('shop_link_url', models.CharField(blank=True, default='#', help_text="Use '#', relative path (e.g., /categories/), or full URL.", max_length=500, verbose_name='Shop link URL')),
                ('shop_link_open_in_new_tab', models.BooleanField(default=False, help_text='If enabled, the shop link opens in a new browser tab.', verbose_name='Shop link opens in new tab')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower number = higher priority).', verbose_name='Order')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='homepage.homepagesection')),
            ],
            options={
                'verbose_name': 'historical Category Box',
                'verbose_name_plural': 'historical Category Boxes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HomepageSectionCategoryBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="Box title (e.g., 'Top categories', 'Shop consumer electronics'). Keep it short (2–4 words).", max_length=255, verbose_name='Title')),
                ('shop_link_text', models.CharField(default='Shop now', help_text="Text for the link at the bottom (e.g., 'Shop now', 'Browse all').", max_length=100, verbose_name='Shop link text')),
                ('shop_link_url', models.CharField(blank=True, default='#', help_text="Use '#', relative path (e.g., /categories/), or full URL.", max_length=500, verbose_name='Shop link URL')),
                ('shop_link_open_in_new_tab', models.BooleanField(default=False, help_text='If enabled, the shop link opens in a new browser tab.', verbose_name='Shop link opens in new tab')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower number = higher priority).', verbose_name='Order')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_boxes', to='homepage.homepagesection')),
            ],
            options={
                'verbose_name': 'Category Box',
                'verbose_name_plural': 'Category Boxes',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalHomepageSectionCategoryItem',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(help_text="Item name (e.g., 'Computers', 'Gaming').", max_length=100, verbose_name='Name')),
                ('image', models.TextField(help_text='Item image. Supported formats: SVG (recommended), PNG, JPG, WEBP. SVG works best for crisp icons. Example file: category_computers.svg.', max_length=100, verbose_name='Image')),
                ('url', models.CharField(blank=True, default='#', help_text="Use '#', relative path (e.g., /c/computers/), or full URL.", max_length=500, verbose_name='URL')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='If enabled, the item link opens in a new browser tab.', verbose_name='Open in new tab')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower number = higher priority).', verbose_name='Order')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category_box', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='homepage.homepagesectioncategorybox')),
            ],
            options={
                'verbose_name': 'historical Category Item',
                'verbose_name_plural': 'historical Category Items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HomepageSectionCategoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Item name (e.g., 'Computers', 'Gaming').", max_length=100, verbose_name='Name')),
                ('image', models.ImageField(help_text='Item image. Supported formats: SVG (recommended), PNG, JPG, WEBP. SVG works best for crisp icons. Example file: category_computers.svg.', storage=apps.media.storage.DynamicMediaStorage(), upload_to=apps.homepage.models._get_section_category_image_filename, verbose_name='Image')),
                ('url', models.CharField(blank=True, default='#', help_text="Use '#', relative path (e.g., /c/computers/), or full URL.", max_length=500, verbose_name='URL')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='If enabled, the item link opens in a new browser tab.', verbose_name='Open in new tab')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower number = higher priority).', verbose_name='Order')),
                ('category_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='homepage.homepagesectioncategorybox')),
            ],
            options={
                'verbose_name': 'Category Item',
                'verbose_name_plural': 'Category Items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
