# Generated by Django 6.0 on 2026-01-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_storefront_hero_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhomepagesection',
            name='section_type',
            field=models.CharField(choices=[('product_list', 'Product list'), ('product_slider', 'Product slider'), ('banner_section', 'Banner section'), ('custom_section', 'Custom section'), ('storefront_hero', 'Storefront hero')], default='product_list', max_length=50, verbose_name='Section type'),
        ),
        migrations.AlterField(
            model_name='historicalhomepagesectioncategorybox',
            name='shop_link_text',
            field=models.CharField(blank=True, default='', help_text="Text for the link at the bottom (e.g., 'Shop now', 'Browse all').", max_length=100, verbose_name='Shop link text'),
        ),
        migrations.AlterField(
            model_name='historicalstorefrontcategorybox',
            name='shop_link_text',
            field=models.CharField(blank=True, default='', help_text="Text for the link at the bottom (e.g., 'Shop now', 'Browse all').", max_length=100, verbose_name='Shop link text'),
        ),
        migrations.AlterField(
            model_name='historicalstorefrontherosection',
            name='primary_button_text',
            field=models.CharField(blank=True, default='', help_text='Text displayed on the primary CTA button.', max_length=100, verbose_name='Primary button text'),
        ),
        migrations.AlterField(
            model_name='historicalstorefrontherosection',
            name='secondary_button_text',
            field=models.CharField(blank=True, default='', help_text='Text displayed on the secondary outline button.', max_length=100, verbose_name='Secondary button text'),
        ),
        migrations.AlterField(
            model_name='historicalstorefrontherosection',
            name='subtitle',
            field=models.TextField(blank=True, default='', help_text='Description text below the title.', verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='historicalstorefrontherosection',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Main headline displayed on the left side.', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(choices=[('product_list', 'Product list'), ('product_slider', 'Product slider'), ('banner_section', 'Banner section'), ('custom_section', 'Custom section'), ('storefront_hero', 'Storefront hero')], default='product_list', max_length=50, verbose_name='Section type'),
        ),
        migrations.AlterField(
            model_name='homepagesectioncategorybox',
            name='shop_link_text',
            field=models.CharField(blank=True, default='', help_text="Text for the link at the bottom (e.g., 'Shop now', 'Browse all').", max_length=100, verbose_name='Shop link text'),
        ),
        migrations.AlterField(
            model_name='storefrontcategorybox',
            name='shop_link_text',
            field=models.CharField(blank=True, default='', help_text="Text for the link at the bottom (e.g., 'Shop now', 'Browse all').", max_length=100, verbose_name='Shop link text'),
        ),
        migrations.AlterField(
            model_name='storefrontherosection',
            name='primary_button_text',
            field=models.CharField(blank=True, default='', help_text='Text displayed on the primary CTA button.', max_length=100, verbose_name='Primary button text'),
        ),
        migrations.AlterField(
            model_name='storefrontherosection',
            name='secondary_button_text',
            field=models.CharField(blank=True, default='', help_text='Text displayed on the secondary outline button.', max_length=100, verbose_name='Secondary button text'),
        ),
        migrations.AlterField(
            model_name='storefrontherosection',
            name='subtitle',
            field=models.TextField(blank=True, default='', help_text='Description text below the title.', verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='storefrontherosection',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Main headline displayed on the left side.', max_length=255, verbose_name='Title'),
        ),
    ]
