# Generated by Django 6.0 on 2026-01-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_remove_hardcoded_content_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='badge_label',
            field=models.CharField(blank=True, default='', help_text="Small badge label (e.g., 'Sale', 'Offer', 'New'). Hero Overlay only.", max_length=50, verbose_name='Badge Label'),
        ),
        migrations.AddField(
            model_name='banner',
            name='badge_text',
            field=models.CharField(blank=True, default='', help_text="Text next to the badge (e.g., 'Up to 30% OFF'). Hero Overlay only.", max_length=100, verbose_name='Badge Text'),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('classic', 'Classic (Image only)'), ('hero_overlay', 'Hero Overlay (Text on image)')], default='classic', help_text="Choose 'Classic' for image-only banners or 'Hero Overlay' for text over image style.", max_length=20, verbose_name='Banner Type'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_icon',
            field=models.CharField(blank=True, default='', help_text="Optional icon for button (e.g., 'location', 'play', 'arrow'). Hero Overlay only.", max_length=50, verbose_name='Button Icon'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, default='', help_text='Primary CTA button text (Hero Overlay only).', max_length=50, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_url',
            field=models.CharField(blank=True, default='#', help_text="URL for the primary button. Use '#', relative path, or full URL.", max_length=500, verbose_name='Button URL'),
        ),
        migrations.AddField(
            model_name='banner',
            name='content_position',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', help_text='Position of text content on the banner (Hero Overlay only).', max_length=10, verbose_name='Content Position'),
        ),
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description text displayed below the headline (Hero Overlay only).', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='banner',
            name='headline',
            field=models.CharField(blank=True, default='', help_text='Main headline text displayed on the banner (Hero Overlay only).', max_length=255, verbose_name='Headline'),
        ),
        migrations.AddField(
            model_name='banner',
            name='secondary_button_text',
            field=models.CharField(blank=True, default='', help_text='Secondary CTA button text (Hero Overlay only).', max_length=50, verbose_name='Secondary Button Text'),
        ),
        migrations.AddField(
            model_name='banner',
            name='secondary_button_url',
            field=models.CharField(blank=True, default='#', help_text='URL for the secondary button.', max_length=500, verbose_name='Secondary Button URL'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='badge_label',
            field=models.CharField(blank=True, default='', help_text="Small badge label (e.g., 'Sale', 'Offer', 'New'). Hero Overlay only.", max_length=50, verbose_name='Badge Label'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='badge_text',
            field=models.CharField(blank=True, default='', help_text="Text next to the badge (e.g., 'Up to 30% OFF'). Hero Overlay only.", max_length=100, verbose_name='Badge Text'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='banner_type',
            field=models.CharField(choices=[('classic', 'Classic (Image only)'), ('hero_overlay', 'Hero Overlay (Text on image)')], default='classic', help_text="Choose 'Classic' for image-only banners or 'Hero Overlay' for text over image style.", max_length=20, verbose_name='Banner Type'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='button_icon',
            field=models.CharField(blank=True, default='', help_text="Optional icon for button (e.g., 'location', 'play', 'arrow'). Hero Overlay only.", max_length=50, verbose_name='Button Icon'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='button_text',
            field=models.CharField(blank=True, default='', help_text='Primary CTA button text (Hero Overlay only).', max_length=50, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='button_url',
            field=models.CharField(blank=True, default='#', help_text="URL for the primary button. Use '#', relative path, or full URL.", max_length=500, verbose_name='Button URL'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='content_position',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', help_text='Position of text content on the banner (Hero Overlay only).', max_length=10, verbose_name='Content Position'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description text displayed below the headline (Hero Overlay only).', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='headline',
            field=models.CharField(blank=True, default='', help_text='Main headline text displayed on the banner (Hero Overlay only).', max_length=255, verbose_name='Headline'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='secondary_button_text',
            field=models.CharField(blank=True, default='', help_text='Secondary CTA button text (Hero Overlay only).', max_length=50, verbose_name='Secondary Button Text'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='secondary_button_url',
            field=models.CharField(blank=True, default='#', help_text='URL for the secondary button.', max_length=500, verbose_name='Secondary Button URL'),
        ),
    ]
