# Generated by Django 6.0 on 2026-01-29 09:57

import apps.homepage.models
import apps.media.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_add_banner_type_and_overlay_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='button_icon',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='content_position',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='historicalbanner',
            name='button_icon',
        ),
        migrations.RemoveField(
            model_name='historicalbanner',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='historicalbanner',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='historicalbanner',
            name='content_position',
        ),
        migrations.RemoveField(
            model_name='historicalbanner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalbanner',
            name='headline',
        ),
        migrations.AddField(
            model_name='banner',
            name='overlay_opacity',
            field=models.PositiveIntegerField(default=50, help_text='Darkness of the overlay behind text (0-100). Higher = darker.', verbose_name='Overlay opacity (%)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='primary_button_icon',
            field=models.CharField(blank=True, default='', help_text="Icon name (e.g., 'location', 'play', 'arrow-right'). Leave empty for no icon.", max_length=50, verbose_name='Primary button icon'),
        ),
        migrations.AddField(
            model_name='banner',
            name='primary_button_open_in_new_tab',
            field=models.BooleanField(default=False, verbose_name='Primary button opens in new tab'),
        ),
        migrations.AddField(
            model_name='banner',
            name='primary_button_text',
            field=models.CharField(blank=True, default='', help_text='Text displayed on the primary button.', max_length=100, verbose_name='Primary button text'),
        ),
        migrations.AddField(
            model_name='banner',
            name='primary_button_url',
            field=models.CharField(blank=True, default='#', help_text="Use '#', relative path (e.g., /shop/), or full URL.", max_length=500, verbose_name='Primary button URL'),
        ),
        migrations.AddField(
            model_name='banner',
            name='secondary_button_icon',
            field=models.CharField(blank=True, default='', help_text="Icon name (e.g., 'play', 'arrow-right'). Leave empty for no icon.", max_length=50, verbose_name='Secondary button icon'),
        ),
        migrations.AddField(
            model_name='banner',
            name='secondary_button_open_in_new_tab',
            field=models.BooleanField(default=False, verbose_name='Secondary button opens in new tab'),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle',
            field=models.TextField(blank=True, default='', help_text='Description text below the title.', verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='banner',
            name='text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', help_text='Position of the text content on the banner.', max_length=10, verbose_name='Text alignment'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Main headline text displayed on the banner.', max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='overlay_opacity',
            field=models.PositiveIntegerField(default=50, help_text='Darkness of the overlay behind text (0-100). Higher = darker.', verbose_name='Overlay opacity (%)'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='primary_button_icon',
            field=models.CharField(blank=True, default='', help_text="Icon name (e.g., 'location', 'play', 'arrow-right'). Leave empty for no icon.", max_length=50, verbose_name='Primary button icon'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='primary_button_open_in_new_tab',
            field=models.BooleanField(default=False, verbose_name='Primary button opens in new tab'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='primary_button_text',
            field=models.CharField(blank=True, default='', help_text='Text displayed on the primary button.', max_length=100, verbose_name='Primary button text'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='primary_button_url',
            field=models.CharField(blank=True, default='#', help_text="Use '#', relative path (e.g., /shop/), or full URL.", max_length=500, verbose_name='Primary button URL'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='secondary_button_icon',
            field=models.CharField(blank=True, default='', help_text="Icon name (e.g., 'play', 'arrow-right'). Leave empty for no icon.", max_length=50, verbose_name='Secondary button icon'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='secondary_button_open_in_new_tab',
            field=models.BooleanField(default=False, verbose_name='Secondary button opens in new tab'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='subtitle',
            field=models.TextField(blank=True, default='', help_text='Description text below the title.', verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', help_text='Position of the text content on the banner.', max_length=10, verbose_name='Text alignment'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Main headline text displayed on the banner.', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='badge_label',
            field=models.CharField(blank=True, default='', help_text="Short label for the badge (e.g., 'Sale', 'Offer', 'New arrival').", max_length=50, verbose_name='Badge label'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='badge_text',
            field=models.CharField(blank=True, default='', help_text="Additional text next to the badge (e.g., 'Save $25 when you spend $250').", max_length=200, verbose_name='Badge text'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('simple', 'Simple (image only)'), ('content', 'Content (image with text overlay)')], default='simple', help_text='Simple: image only. Content: image with text overlay, badge, and buttons.', max_length=20, verbose_name='Banner type'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Desktop banner. Recommended size: 1920x512 pixels. Displayed on screens wider than 768px. Images scale to fill the width; the height adjusts automatically to maintain proportions.', storage=apps.media.storage.DynamicMediaStorage(), upload_to=apps.homepage.models._get_banner_filename, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='secondary_button_text',
            field=models.CharField(blank=True, default='', help_text='Text displayed on the secondary button.', max_length=100, verbose_name='Secondary button text'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='secondary_button_url',
            field=models.CharField(blank=True, default='#', help_text="Use '#', relative path, or full URL.", max_length=500, verbose_name='Secondary button URL'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, default='', help_text='URL to redirect when the banner is clicked (for simple banners)', max_length=500, verbose_name='Target URL'),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='badge_label',
            field=models.CharField(blank=True, default='', help_text="Short label for the badge (e.g., 'Sale', 'Offer', 'New arrival').", max_length=50, verbose_name='Badge label'),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='badge_text',
            field=models.CharField(blank=True, default='', help_text="Additional text next to the badge (e.g., 'Save $25 when you spend $250').", max_length=200, verbose_name='Badge text'),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='banner_type',
            field=models.CharField(choices=[('simple', 'Simple (image only)'), ('content', 'Content (image with text overlay)')], default='simple', help_text='Simple: image only. Content: image with text overlay, badge, and buttons.', max_length=20, verbose_name='Banner type'),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='image',
            field=models.TextField(help_text='Desktop banner. Recommended size: 1920x512 pixels. Displayed on screens wider than 768px. Images scale to fill the width; the height adjusts automatically to maintain proportions.', max_length=100, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='secondary_button_text',
            field=models.CharField(blank=True, default='', help_text='Text displayed on the secondary button.', max_length=100, verbose_name='Secondary button text'),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='secondary_button_url',
            field=models.CharField(blank=True, default='#', help_text="Use '#', relative path, or full URL.", max_length=500, verbose_name='Secondary button URL'),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='url',
            field=models.URLField(blank=True, default='', help_text='URL to redirect when the banner is clicked (for simple banners)', max_length=500, verbose_name='Target URL'),
        ),
    ]
