# Generated by Django 6.0 on 2026-01-29 11:33

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def create_carousels_and_migrate_banners(apps, schema_editor):
    """Create the two BannerCarousel types and migrate existing banners."""
    BannerCarousel = apps.get_model('homepage', 'BannerCarousel')
    Banner = apps.get_model('homepage', 'Banner')
    
    # Create both carousel types
    simple_carousel, _ = BannerCarousel.objects.get_or_create(
        banner_type='simple',
        defaults={'is_active': False}
    )
    content_carousel, _ = BannerCarousel.objects.get_or_create(
        banner_type='content',
        defaults={'is_active': True}  # Content banners were active in seed
    )
    
    # Migrate existing banners to their appropriate carousel
    for banner in Banner.objects.all():
        if hasattr(banner, 'banner_type') and banner.banner_type == 'content':
            banner.carousel = content_carousel
        else:
            banner.carousel = simple_carousel
        banner.save()


def reverse_migration(apps, schema_editor):
    """Reverse the data migration - restore banner_type field."""
    Banner = apps.get_model('homepage', 'Banner')
    
    for banner in Banner.objects.filter(carousel__isnull=False):
        banner.banner_type = banner.carousel.banner_type
        banner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_add_banner_type_and_content_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Create BannerCarousel model
        migrations.CreateModel(
            name='BannerCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banner_type', models.CharField(choices=[('simple', 'Simple (image only)'), ('content', 'Content (image with text overlay)')], help_text='Simple: image only. Content: image with text overlay, badge, and buttons.', max_length=20, unique=True, verbose_name='Banner type')),
                ('is_active', models.BooleanField(default=False, help_text='Only one carousel can be active at a time.', verbose_name='Active')),
                ('available_from', models.DateTimeField(blank=True, help_text='Start date and time for carousel display (leave empty for immediate display)', null=True, verbose_name='Available from')),
                ('available_to', models.DateTimeField(blank=True, help_text='End date and time for carousel display (leave empty for no end date)', null=True, verbose_name='Available to')),
            ],
            options={
                'verbose_name': 'Banner Carousel',
                'verbose_name_plural': 'Banner Carousels',
                'ordering': ['banner_type'],
            },
        ),
        # Step 2: Add carousel FK to Banner (nullable for now)
        migrations.AddField(
            model_name='banner',
            name='carousel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='homepage.bannercarousel', verbose_name='Carousel'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='carousel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='homepage.bannercarousel', verbose_name='Carousel'),
        ),
        # Step 3: Migrate data - create carousels and assign banners
        migrations.RunPython(create_carousels_and_migrate_banners, reverse_migration),
        # Step 4: Now we can safely remove the old fields
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='historicalbanner',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Banner', 'verbose_name_plural': 'historical Banners'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='available_to',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='banner_type',
        ),
        migrations.RemoveField(
            model_name='historicalbanner',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='historicalbanner',
            name='available_to',
        ),
        migrations.RemoveField(
            model_name='historicalbanner',
            name='banner_type',
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center')], default='left', help_text='Position of the text content on the banner.', max_length=10, verbose_name='Text alignment'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.CharField(blank=True, default='', help_text='URL to redirect when the banner is clicked (for simple banners)', max_length=500, verbose_name='Target URL'),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center')], default='left', help_text='Position of the text content on the banner.', max_length=10, verbose_name='Text alignment'),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='url',
            field=models.CharField(blank=True, default='', help_text='URL to redirect when the banner is clicked (for simple banners)', max_length=500, verbose_name='Target URL'),
        ),
        # Step 5: Create historical model for BannerCarousel
        migrations.CreateModel(
            name='HistoricalBannerCarousel',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('banner_type', models.CharField(choices=[('simple', 'Simple (image only)'), ('content', 'Content (image with text overlay)')], db_index=True, help_text='Simple: image only. Content: image with text overlay, badge, and buttons.', max_length=20, verbose_name='Banner type')),
                ('is_active', models.BooleanField(default=False, help_text='Only one carousel can be active at a time.', verbose_name='Active')),
                ('available_from', models.DateTimeField(blank=True, help_text='Start date and time for carousel display (leave empty for immediate display)', null=True, verbose_name='Available from')),
                ('available_to', models.DateTimeField(blank=True, help_text='End date and time for carousel display (leave empty for no end date)', null=True, verbose_name='Available to')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Banner Carousel',
                'verbose_name_plural': 'historical Banner Carousels',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
