# Generated by Django 6.0 on 2026-01-29 12:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def migrate_carousel_to_banner_type(apps, schema_editor):
    """Copy banner_type from carousel to banner, and create BannerSettings."""
    BannerCarousel = apps.get_model('homepage', 'BannerCarousel')
    Banner = apps.get_model('homepage', 'Banner')
    BannerSettings = apps.get_model('homepage', 'BannerSettings')
    
    # Find the active carousel type to set in BannerSettings
    active_carousel = BannerCarousel.objects.filter(is_active=True).first()
    active_type = active_carousel.banner_type if active_carousel else 'content'
    
    # Get availability from active carousel
    available_from = active_carousel.available_from if active_carousel else None
    available_to = active_carousel.available_to if active_carousel else None
    
    # Create singleton BannerSettings
    BannerSettings.objects.create(
        id=1,
        active_banner_type=active_type,
        available_from=available_from,
        available_to=available_to,
    )
    
    # Copy banner_type from carousel to each banner
    for banner in Banner.objects.filter(carousel__isnull=False):
        banner.banner_type = banner.carousel.banner_type
        banner.save()


def reverse_migration(apps, schema_editor):
    """Reverse - restore carousel FK and delete BannerSettings."""
    BannerCarousel = apps.get_model('homepage', 'BannerCarousel')
    Banner = apps.get_model('homepage', 'Banner')
    BannerSettings = apps.get_model('homepage', 'BannerSettings')
    
    # Get settings to determine which carousel should be active
    settings_obj = BannerSettings.objects.first()
    active_type = settings_obj.active_banner_type if settings_obj else 'content'
    
    # Ensure carousels exist
    simple_carousel, _ = BannerCarousel.objects.get_or_create(
        banner_type='simple',
        defaults={'is_active': active_type == 'simple'}
    )
    content_carousel, _ = BannerCarousel.objects.get_or_create(
        banner_type='content',
        defaults={'is_active': active_type == 'content'}
    )
    
    # Assign banners to carousels based on their banner_type
    for banner in Banner.objects.all():
        if banner.banner_type == 'simple':
            banner.carousel = simple_carousel
        else:
            banner.carousel = content_carousel
        banner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_banner_carousel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Create BannerSettings singleton model
        migrations.CreateModel(
            name='BannerSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_banner_type', models.CharField(
                    choices=[('simple', 'Simple (image only)'), ('content', 'Content (image with text overlay)')],
                    default='content',
                    help_text='Which banner type should be displayed on the storefront.',
                    max_length=20,
                    verbose_name='Active banner type'
                )),
                ('available_from', models.DateTimeField(
                    blank=True,
                    help_text='Start date and time for banner display (leave empty for immediate display)',
                    null=True,
                    verbose_name='Available from'
                )),
                ('available_to', models.DateTimeField(
                    blank=True,
                    help_text='End date and time for banner display (leave empty for no end date)',
                    null=True,
                    verbose_name='Available to'
                )),
            ],
            options={
                'verbose_name': 'Banner Settings',
                'verbose_name_plural': 'Banner Settings',
            },
        ),
        # Step 2: Create historical model for BannerSettings
        migrations.CreateModel(
            name='HistoricalBannerSettings',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('active_banner_type', models.CharField(
                    choices=[('simple', 'Simple (image only)'), ('content', 'Content (image with text overlay)')],
                    default='content',
                    help_text='Which banner type should be displayed on the storefront.',
                    max_length=20,
                    verbose_name='Active banner type'
                )),
                ('available_from', models.DateTimeField(
                    blank=True,
                    help_text='Start date and time for banner display (leave empty for immediate display)',
                    null=True,
                    verbose_name='Available from'
                )),
                ('available_to', models.DateTimeField(
                    blank=True,
                    help_text='End date and time for banner display (leave empty for no end date)',
                    null=True,
                    verbose_name='Available to'
                )),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Banner Settings',
                'verbose_name_plural': 'historical Banner Settings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        # Step 3: Add banner_type back to Banner model
        migrations.AddField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(
                choices=[('simple', 'Simple (image only)'), ('content', 'Content (image with text overlay)')],
                default='content',
                help_text='Simple: image only, links to URL on click. Content: image with text overlay, badge, and buttons.',
                max_length=20,
                verbose_name='Banner type'
            ),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='banner_type',
            field=models.CharField(
                choices=[('simple', 'Simple (image only)'), ('content', 'Content (image with text overlay)')],
                default='content',
                help_text='Simple: image only, links to URL on click. Content: image with text overlay, badge, and buttons.',
                max_length=20,
                verbose_name='Banner type'
            ),
        ),
        # Step 4: Add available_from/available_to back to Banner model
        migrations.AddField(
            model_name='banner',
            name='available_from',
            field=models.DateTimeField(
                blank=True,
                help_text='Start date and time for banner display (leave empty for immediate display)',
                null=True,
                verbose_name='Available from'
            ),
        ),
        migrations.AddField(
            model_name='banner',
            name='available_to',
            field=models.DateTimeField(
                blank=True,
                help_text='End date and time for banner display (leave empty for no end date)',
                null=True,
                verbose_name='Available to'
            ),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='available_from',
            field=models.DateTimeField(
                blank=True,
                help_text='Start date and time for banner display (leave empty for immediate display)',
                null=True,
                verbose_name='Available from'
            ),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='available_to',
            field=models.DateTimeField(
                blank=True,
                help_text='End date and time for banner display (leave empty for no end date)',
                null=True,
                verbose_name='Available to'
            ),
        ),
        # Step 5: Update Banner ordering
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['banner_type', 'order', '-created_at'], 'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        # Step 6: Migrate data - copy banner_type from carousel to banner
        migrations.RunPython(migrate_carousel_to_banner_type, reverse_migration),
        # Step 7: Remove carousel FK from Banner
        migrations.RemoveField(
            model_name='banner',
            name='carousel',
        ),
        migrations.RemoveField(
            model_name='historicalbanner',
            name='carousel',
        ),
        # Step 8: Delete BannerCarousel and its history
        migrations.DeleteModel(
            name='HistoricalBannerCarousel',
        ),
        migrations.DeleteModel(
            name='BannerCarousel',
        ),
    ]
