# Generated by Django 6.0 on 2026-01-29 12:26

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_revert_bannercarousel_to_bannersettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banner_type', models.CharField(choices=[('simple', 'Standard banner'), ('content', 'Full hero banner')], max_length=20, unique=True, verbose_name='Banner type')),
                ('is_active', models.BooleanField(default=False, help_text="Only one banner group can be active at a time. Active group's banners are displayed on the homepage.", verbose_name='Active')),
                ('available_from', models.DateTimeField(blank=True, help_text='Start date and time for banner display (leave empty for immediate display)', null=True, verbose_name='Available from')),
                ('available_to', models.DateTimeField(blank=True, help_text='End date and time for banner display (leave empty for no end date)', null=True, verbose_name='Available to')),
            ],
            options={
                'verbose_name': 'Banner Group',
                'verbose_name_plural': 'Banner Groups',
                'ordering': ['-banner_type'],
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('simple', 'Standard banner'), ('content', 'Full hero banner')], default='simple', help_text='Standard banner: image only with optional link. Full hero banner: full-screen image with text overlay, badge, and buttons.', max_length=20, verbose_name='Banner type'),
        ),
        migrations.AlterField(
            model_name='bannersettings',
            name='active_banner_type',
            field=models.CharField(choices=[('simple', 'Standard banner'), ('content', 'Full hero banner')], default='content', help_text='Select which type of banners to display on the homepage.', max_length=20, verbose_name='Active banner type'),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='banner_type',
            field=models.CharField(choices=[('simple', 'Standard banner'), ('content', 'Full hero banner')], default='simple', help_text='Standard banner: image only with optional link. Full hero banner: full-screen image with text overlay, badge, and buttons.', max_length=20, verbose_name='Banner type'),
        ),
        migrations.AlterField(
            model_name='historicalbannersettings',
            name='active_banner_type',
            field=models.CharField(choices=[('simple', 'Standard banner'), ('content', 'Full hero banner')], default='content', help_text='Select which type of banners to display on the homepage.', max_length=20, verbose_name='Active banner type'),
        ),
        migrations.AddField(
            model_name='banner',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The banner group this banner belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='homepage.bannergroup', verbose_name='Banner group'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The banner group this banner belongs to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='homepage.bannergroup', verbose_name='Banner group'),
        ),
        migrations.CreateModel(
            name='HistoricalBannerGroup',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('banner_type', models.CharField(choices=[('simple', 'Standard banner'), ('content', 'Full hero banner')], db_index=True, max_length=20, verbose_name='Banner type')),
                ('is_active', models.BooleanField(default=False, help_text="Only one banner group can be active at a time. Active group's banners are displayed on the homepage.", verbose_name='Active')),
                ('available_from', models.DateTimeField(blank=True, help_text='Start date and time for banner display (leave empty for immediate display)', null=True, verbose_name='Available from')),
                ('available_to', models.DateTimeField(blank=True, help_text='End date and time for banner display (leave empty for no end date)', null=True, verbose_name='Available to')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Banner Group',
                'verbose_name_plural': 'historical Banner Groups',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
