# Generated by Django 6.0 on 2026-01-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_add_banner_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_alignment',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', help_text='How the image is aligned within its container (object-position).', max_length=10, verbose_name='Image alignment'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='image_alignment',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', help_text='How the image is aligned within its container (object-position).', max_length=10, verbose_name='Image alignment'),
        ),
    ]
