# Generated by Django 6.0 on 2026-02-17 15:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_historical_css_hook_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalbanner',
            name='css_hook',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalhomepagesection',
            name='css_hook',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalhomepagesectionbanner',
            name='css_hook',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalhomepagesectioncategorybox',
            name='css_hook',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalhomepagesectioncategoryitem',
            name='css_hook',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalstorefrontcategorybox',
            name='css_hook',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalstorefrontcategoryitem',
            name='css_hook',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalstorefrontherosection',
            name='css_hook',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
