# Generated by Django 6.0 on 2026-02-13 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_delivery_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('default_payment_time', models.PositiveIntegerField(blank=True, help_text='Payment time in days', null=True)),
                ('additional_fees', models.DecimalField(blank=True, decimal_places=2, help_text='Additional fee for this payment method', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.paymentmethod'),
        ),
    ]
