# Generated by Django 6.0 on 2026-02-16 18:12

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iso2', models.CharField(db_index=True, max_length=2, unique=True, verbose_name='ISO2')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('dial_code', models.CharField(blank=True, default='', max_length=10, verbose_name='Dial code')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Shipping country',
                'verbose_name_plural': 'Shipping countries',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='tax_rate_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='cart',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='HistoricalShippingCountry',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('iso2', models.CharField(db_index=True, max_length=2, verbose_name='ISO2')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('dial_code', models.CharField(blank=True, default='', max_length=10, verbose_name='Dial code')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Shipping country',
                'verbose_name_plural': 'historical Shipping countries',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalShippingZone',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='Name')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Shipping zone',
                'verbose_name_plural': 'historical Shipping zones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('countries', models.ManyToManyField(blank=True, related_name='zones', to='cart.shippingcountry', verbose_name='Countries')),
            ],
            options={
                'verbose_name': 'Shipping zone',
                'verbose_name_plural': 'Shipping zones',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='zones',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to make this method available for all zones.', related_name='delivery_methods', to='cart.shippingzone', verbose_name='Shipping zones'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='zones',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to make this method available for all zones.', related_name='payment_methods', to='cart.shippingzone', verbose_name='Shipping zones'),
        ),
    ]
