# Generated by Django 6.0 on 2026-02-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_shippingcountry_cart_coupon_code_cart_discount_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingzone',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='deliverymethod',
            name='zones',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='zones',
        ),
        migrations.DeleteModel(
            name='HistoricalShippingZone',
        ),
        migrations.DeleteModel(
            name='ShippingZone',
        ),
    ]
