# Generated by Django 6.0 on 2026-02-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_shippingzone_countries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='countries',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to make this method available for all countries.', related_name='delivery_methods', to='cart.shippingcountry', verbose_name='Shipping countries'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='countries',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to make this method available for all countries.', related_name='payment_methods', to='cart.shippingcountry', verbose_name='Shipping countries'),
        ),
    ]
