# Generated by Django 6.0 on 2026-02-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_deliverymethod_countries_paymentmethod_countries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingcountry',
            options={'ordering': ['name'], 'verbose_name': 'Shipping country', 'verbose_name_plural': 'Shipping countries'},
        ),
        migrations.RemoveField(
            model_name='historicalshippingcountry',
            name='dial_code',
        ),
        migrations.RemoveField(
            model_name='historicalshippingcountry',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='shippingcountry',
            name='dial_code',
        ),
        migrations.RemoveField(
            model_name='shippingcountry',
            name='sort_order',
        ),
    ]
