# Generated by Django 6.0 on 2026-02-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_shippingcountry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshippingcountry',
            name='iso2',
            field=models.CharField(db_index=True, help_text='Two-letter ISO 3166-1 alpha-2 country code (e.g. PL, DE). Used to match tax rates and to enable/disable checkout options per country.', max_length=2, verbose_name='ISO2'),
        ),
        migrations.AlterField(
            model_name='shippingcountry',
            name='iso2',
            field=models.CharField(db_index=True, help_text='Two-letter ISO 3166-1 alpha-2 country code (e.g. PL, DE). Used to match tax rates and to enable/disable checkout options per country.', max_length=2, unique=True, verbose_name='ISO2'),
        ),
    ]
