# Generated by Django 6.0 on 2026-02-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_remove_shippingcountry_and_countries_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='tax_rate_percent',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='tax_total',
        ),
        migrations.DeleteModel(
            name='HistoricalShippingCountry',
        ),
    ]
