# Generated by Django 6.0 on 2026-05-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveAssistedSalesSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('las_base_url', models.URLField(blank=True, max_length=500)),
                ('store_api_key', models.CharField(blank=True, max_length=128)),
                ('last_test_status', models.CharField(blank=True, max_length=32)),
                ('last_test_message', models.TextField(blank=True)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Live Assisted Sales settings',
                'verbose_name_plural': 'Live Assisted Sales settings',
            },
        ),
    ]
