# Generated by Django 6.0 on 2026-05-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_assisted_sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveassistedsalessettings',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='liveassistedsalessettings',
            name='las_base_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='LAS base URL'),
        ),
        migrations.AlterField(
            model_name='liveassistedsalessettings',
            name='last_test_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last test at'),
        ),
        migrations.AlterField(
            model_name='liveassistedsalessettings',
            name='last_test_message',
            field=models.TextField(blank=True, verbose_name='Last test message'),
        ),
        migrations.AlterField(
            model_name='liveassistedsalessettings',
            name='last_test_status',
            field=models.CharField(blank=True, max_length=32, verbose_name='Last test status'),
        ),
        migrations.AlterField(
            model_name='liveassistedsalessettings',
            name='store_api_key',
            field=models.CharField(blank=True, max_length=128, verbose_name='Store API key'),
        ),
    ]
