# Generated by Codex on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live_assisted_sales", "0002_alter_liveassistedsalessettings_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="liveassistedsalessettings",
            name="site_public_key",
            field=models.CharField(blank=True, max_length=80, verbose_name="Site public key"),
        ),
    ]
