# Generated by Django 6.0 on 2026-07-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_assisted_sales', '0005_outboxevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveassistedsalessettings',
            name='mirror_base_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Mirror LAS base URL'),
        ),
        migrations.AddField(
            model_name='liveassistedsalessettings',
            name='mirror_store_api_key',
            field=models.CharField(blank=True, max_length=128, verbose_name='Mirror store API key'),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='target',
            field=models.CharField(choices=[('primary', 'Primary'), ('mirror', 'Mirror')], default='primary', max_length=16),
        ),
    ]
