# Generated by Django 6.0 on 2026-02-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0001_create_historicalcoupon"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DROP TABLE IF EXISTS promotions_historicalcoupon CASCADE;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
