# Generated by Django 6.0 on 2026-02-17 14:45

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0012_alter_coupon_min_subtotal_and_more'),
        ('promotions', '0002_drop_historicalcoupon_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.coupon',),
        ),
        migrations.CreateModel(
            name='HistoricalCoupon',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Code')),
                ('kind', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], default='percent', help_text='Percent reduces subtotal by a percentage. Fixed reduces subtotal by a currency amount.', max_length=20, verbose_name='Type')),
                ('value', models.DecimalField(decimal_places=2, help_text='For Percent: enter 10 for 10%. For Fixed: enter amount in store currency.', max_digits=10, verbose_name='Value')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('valid_from', models.DateTimeField(blank=True, help_text='Optional start time. Leave empty for immediate availability.', null=True, verbose_name='Valid from')),
                ('valid_to', models.DateTimeField(blank=True, help_text='Optional end time. Leave empty for no expiration.', null=True, verbose_name='Valid to')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Optional. Maximum number of times this coupon can be used.', null=True, verbose_name='Usage limit')),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Number of times the coupon has been used.', verbose_name='Used count')),
                ('min_subtotal', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Coupon is valid only when cart total (before discounts) is at least this amount.', max_digits=10, null=True, verbose_name='Min total')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical coupon',
                'verbose_name_plural': 'historical coupons',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
