# Generated by Django 6.0 on 2026-01-22 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
        ('users', '0002_customuser_language_customuser_timezone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable this provider without deleting it.', verbose_name='Active')),
                ('social_app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to='socialaccount.socialapp', verbose_name='Social App')),
            ],
            options={
                'verbose_name': 'Social App Settings',
                'verbose_name_plural': 'Social App Settings',
            },
        ),
    ]
