# Generated by Django 6.0 on 2026-02-11 11:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_historicalcustomuser_historicalsocialappsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last password change.', null=True, verbose_name='Password last changed'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last password change.', null=True, verbose_name='Password last changed'),
        ),
        migrations.CreateModel(
            name='HistoricalPendingEmailChange',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('new_email', models.EmailField(max_length=254, verbose_name='New email address')),
                ('token', models.CharField(db_index=True, max_length=64, verbose_name='Verification token')),
                ('expires_at', models.DateTimeField(verbose_name='Expires at')),
                ('notified_old_email', models.BooleanField(default=False, help_text='Whether a notification was sent to the old email.', verbose_name='Notified old email')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'historical Pending Email Change',
                'verbose_name_plural': 'historical Pending Email Changes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PendingEmailChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_email', models.EmailField(max_length=254, verbose_name='New email address')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Verification token')),
                ('expires_at', models.DateTimeField(verbose_name='Expires at')),
                ('notified_old_email', models.BooleanField(default=False, help_text='Whether a notification was sent to the old email.', verbose_name='Notified old email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_email_change', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Pending Email Change',
                'verbose_name_plural': 'Pending Email Changes',
            },
        ),
    ]
