# Generated by Django 6.0 on 2026-02-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_pending_email_change_and_password_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
    ]
