# Generated by Django 6.0 on 2026-02-14 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='avatar',
        ),
    ]
