# Generated by Django 6.0 on 2026-02-16 21:33

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_shipping_country_iso2'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalShippingAddress',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_default', models.BooleanField(default=False, help_text='Used as the default shipping address for checkout prefill.', verbose_name='Default')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Phone')),
                ('shipping_country', models.CharField(max_length=120, verbose_name='Country')),
                ('shipping_city', models.CharField(max_length=120, verbose_name='City')),
                ('shipping_address', models.CharField(max_length=255, verbose_name='Shipping address')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'historical Shipping address',
                'verbose_name_plural': 'historical Shipping addresses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(default=False, help_text='Used as the default shipping address for checkout prefill.', verbose_name='Default')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Phone')),
                ('shipping_country', models.CharField(max_length=120, verbose_name='Country')),
                ('shipping_city', models.CharField(max_length=120, verbose_name='City')),
                ('shipping_address', models.CharField(max_length=255, verbose_name='Shipping address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Shipping address',
                'verbose_name_plural': 'Shipping addresses',
                'ordering': ['-is_default', '-updated_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='uniq_default_shipping_address_per_user')],
            },
        ),
    ]
