# Generated by Django 6.0 on 2026-02-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_customuser_shipping_country_iso2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalshippingaddress',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='historicalshippingaddress',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='historicalshippingaddress',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_country',
        ),
        migrations.AddField(
            model_name='historicalshippingaddress',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='historicalshippingaddress',
            name='phone_country_code',
            field=models.CharField(default='+48', max_length=10, verbose_name='Country code'),
        ),
        migrations.AddField(
            model_name='historicalshippingaddress',
            name='phone_number',
            field=models.CharField(default='', max_length=50, verbose_name='Mobile phone'),
        ),
        migrations.AddField(
            model_name='historicalshippingaddress',
            name='shipping_apartment_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Apartment number'),
        ),
        migrations.AddField(
            model_name='historicalshippingaddress',
            name='shipping_building_number',
            field=models.CharField(default='', max_length=30, verbose_name='Building number'),
        ),
        migrations.AddField(
            model_name='historicalshippingaddress',
            name='shipping_postal_code',
            field=models.CharField(default='', max_length=20, verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='historicalshippingaddress',
            name='shipping_street',
            field=models.CharField(default='', max_length=255, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone_country_code',
            field=models.CharField(default='+48', max_length=10, verbose_name='Country code'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.CharField(default='', max_length=50, verbose_name='Mobile phone'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_apartment_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Apartment number'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_building_number',
            field=models.CharField(default='', max_length=30, verbose_name='Building number'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_postal_code',
            field=models.CharField(default='', max_length=20, verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_street',
            field=models.CharField(default='', max_length=255, verbose_name='Street'),
        ),
    ]
