# Generated by Django 6.0 on 2026-02-06 09:49

import apps.favourites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0002_add_share_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwishlist',
            name='share_id',
            field=models.CharField(db_index=True, default=apps.favourites.models._generate_share_id, editable=False, help_text='Unique, non-guessable identifier for sharing', max_length=10, verbose_name='Share ID'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='share_id',
            field=models.CharField(db_index=True, default=apps.favourites.models._generate_share_id, editable=False, help_text='Unique, non-guessable identifier for sharing', max_length=10, unique=True, verbose_name='Share ID'),
        ),
    ]
