# Generated by Django 6.0 on 2026-02-16 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0003_historicalwishlist_share_id_alter_wishlist_share_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalwishlist',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Shopping list', 'verbose_name_plural': 'historical Shopping lists'},
        ),
        migrations.AlterModelOptions(
            name='historicalwishlistitem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Shopping list item', 'verbose_name_plural': 'historical Shopping list items'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-is_default', '-updated_at'], 'verbose_name': 'Shopping list', 'verbose_name_plural': 'Shopping lists'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': 'Shopping list item', 'verbose_name_plural': 'Shopping list items'},
        ),
        migrations.AlterField(
            model_name='historicalwishlist',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Whether this is the default shopping list (Favorites)', verbose_name='Default'),
        ),
        migrations.AlterField(
            model_name='historicalwishlist',
            name='name',
            field=models.CharField(help_text='Name of the shopping list', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalwishlistitem',
            name='price_when_added',
            field=models.DecimalField(decimal_places=2, help_text='The price of the product when it was added to the shopping list', max_digits=15, verbose_name='Price when added'),
        ),
        migrations.AlterField(
            model_name='historicalwishlistitem',
            name='wishlist',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='favourites.wishlist', verbose_name='Shopping list'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Whether this is the default shopping list (Favorites)', verbose_name='Default'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='name',
            field=models.CharField(help_text='Name of the shopping list', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='price_when_added',
            field=models.DecimalField(decimal_places=2, help_text='The price of the product when it was added to the shopping list', max_digits=15, verbose_name='Price when added'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='favourites.wishlist', verbose_name='Shopping list'),
        ),
    ]
