# Generated by Django 6.0 on 2026-01-22 10:21

import apps.media.encryption
import apps.media.models
import apps.media.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaStorageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_type', models.CharField(choices=[('local', 'Local Server Storage'), ('s3', 'Amazon S3')], default='local', max_length=20, verbose_name='storage type')),
                ('aws_access_key_id', models.CharField(blank=True, max_length=200, verbose_name='AWS Access Key ID')),
                ('aws_secret_access_key', apps.media.encryption.EncryptedCharField(blank=True, verbose_name='AWS Secret Access Key')),
                ('aws_bucket_name', models.CharField(blank=True, max_length=63, verbose_name='bucket name')),
                ('aws_region', models.CharField(choices=[('us-east-1', 'US East (N. Virginia)'), ('us-east-2', 'US East (Ohio)'), ('us-west-1', 'US West (N. California)'), ('us-west-2', 'US West (Oregon)'), ('eu-west-1', 'EU (Ireland)'), ('eu-west-2', 'EU (London)'), ('eu-west-3', 'EU (Paris)'), ('eu-central-1', 'EU (Frankfurt)'), ('eu-north-1', 'EU (Stockholm)'), ('ap-northeast-1', 'Asia Pacific (Tokyo)'), ('ap-northeast-2', 'Asia Pacific (Seoul)'), ('ap-southeast-1', 'Asia Pacific (Singapore)'), ('ap-southeast-2', 'Asia Pacific (Sydney)'), ('ap-south-1', 'Asia Pacific (Mumbai)'), ('sa-east-1', 'South America (São Paulo)'), ('ca-central-1', 'Canada (Central)')], default='eu-central-1', max_length=30, verbose_name='AWS region')),
                ('aws_location', models.CharField(blank=True, default='media', max_length=200, verbose_name='storage path')),
                ('cdn_enabled', models.BooleanField(default=False, verbose_name='enable CDN')),
                ('cdn_domain', models.CharField(blank=True, max_length=255, verbose_name='CDN domain')),
            ],
            options={
                'verbose_name': 'Media Storage Settings',
                'verbose_name_plural': 'Media Storage Settings',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(storage=apps.media.storage.DynamicMediaStorage(), upload_to=apps.media.models.media_file_path, verbose_name='file')),
                ('filename', models.CharField(max_length=255, verbose_name='filename')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility (required for images)', max_length=200, verbose_name='alt text')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], db_index=True, default='other', max_length=20, verbose_name='file type')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME type')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes', verbose_name='file size')),
                ('is_archived', models.BooleanField(default=False, help_text='Archived files are hidden but kept in storage.', verbose_name='archived')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media_files', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'media file',
                'verbose_name_plural': 'media files',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file_type', '-created_at'], name='media_media_file_ty_fb018f_idx'), models.Index(fields=['is_archived', '-created_at'], name='media_media_is_arch_ab81f6_idx')],
            },
        ),
    ]
