# Generated by Django 6.0 on 2026-01-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='source_field',
            field=models.CharField(blank=True, help_text="The field name this file was uploaded to (e.g., 'image')", max_length=100, verbose_name='source field'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='source_model',
            field=models.CharField(blank=True, db_index=True, help_text="The model this file was uploaded from (e.g., 'homepage.Banner')", max_length=100, verbose_name='source model'),
        ),
    ]
