# Generated by Django 5.2.10 on 2026-01-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_mediafile_source_field_mediafile_source_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='source_object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='The primary key of the source object', null=True, verbose_name='source object ID'),
        ),
    ]
