# Generated by Django 5.2.10 on 2026-01-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_add_source_object_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mediafile',
            name='media_media_is_arch_ab81f6_idx',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='is_archived',
        ),
    ]
