# Generated by Django 6.0 on 2026-01-28 15:05

import apps.media.encryption
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_remove_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMediaFile',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('file', models.TextField(max_length=100, verbose_name='file')),
                ('filename', models.CharField(max_length=255, verbose_name='filename')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility (required for images)', max_length=200, verbose_name='alt text')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], db_index=True, default='other', max_length=20, verbose_name='file type')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME type')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes', verbose_name='file size')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('source_model', models.CharField(blank=True, db_index=True, help_text="The model this file was uploaded from (e.g., 'homepage.Banner')", max_length=100, verbose_name='source model')),
                ('source_field', models.CharField(blank=True, help_text="The field name this file was uploaded to (e.g., 'image')", max_length=100, verbose_name='source field')),
                ('source_object_id', models.PositiveIntegerField(blank=True, db_index=True, help_text='The primary key of the source object', null=True, verbose_name='source object ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'historical media file',
                'verbose_name_plural': 'historical media files',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMediaStorageSettings',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('provider_type', models.CharField(choices=[('local', 'Local Server Storage'), ('s3', 'Amazon S3')], default='local', max_length=20, verbose_name='storage type')),
                ('aws_access_key_id', models.CharField(blank=True, max_length=200, verbose_name='AWS Access Key ID')),
                ('aws_secret_access_key', apps.media.encryption.EncryptedCharField(blank=True, verbose_name='AWS Secret Access Key')),
                ('aws_bucket_name', models.CharField(blank=True, max_length=63, verbose_name='bucket name')),
                ('aws_region', models.CharField(choices=[('us-east-1', 'US East (N. Virginia)'), ('us-east-2', 'US East (Ohio)'), ('us-west-1', 'US West (N. California)'), ('us-west-2', 'US West (Oregon)'), ('eu-west-1', 'EU (Ireland)'), ('eu-west-2', 'EU (London)'), ('eu-west-3', 'EU (Paris)'), ('eu-central-1', 'EU (Frankfurt)'), ('eu-north-1', 'EU (Stockholm)'), ('ap-northeast-1', 'Asia Pacific (Tokyo)'), ('ap-northeast-2', 'Asia Pacific (Seoul)'), ('ap-southeast-1', 'Asia Pacific (Singapore)'), ('ap-southeast-2', 'Asia Pacific (Sydney)'), ('ap-south-1', 'Asia Pacific (Mumbai)'), ('sa-east-1', 'South America (São Paulo)'), ('ca-central-1', 'Canada (Central)')], default='eu-central-1', max_length=30, verbose_name='AWS region')),
                ('aws_location', models.CharField(blank=True, default='media', max_length=200, verbose_name='storage path')),
                ('cdn_enabled', models.BooleanField(default=False, verbose_name='enable CDN')),
                ('cdn_domain', models.CharField(blank=True, max_length=255, verbose_name='CDN domain')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Media Storage Settings',
                'verbose_name_plural': 'historical Media Storage Settings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
