# Generated by Django 6.0 on 2026-01-22 10:21

import apps.media.storage
import autoslug.fields
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=100)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.attributedefinition')),
            ],
            options={
                'ordering': ['attribute', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('image', models.ImageField(blank=True, null=True, storage=apps.media.storage.DynamicMediaStorage(), upload_to='category-images/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden')], default='hidden', help_text='Controls product page visibility.', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sales_total', models.DecimalField(decimal_places=2, default=0, help_text='Total number of units sold.', max_digits=15, verbose_name='Units sold (total)')),
                ('revenue_total', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue generated.', max_digits=15, verbose_name='Revenue (total)')),
                ('sales_per_day', models.DecimalField(decimal_places=2, default=0, help_text='Average units sold per day.', max_digits=15, verbose_name='Units sold (daily avg)')),
                ('sales_per_month', models.DecimalField(decimal_places=2, default=0, help_text='Average units sold per month.', max_digits=15, verbose_name='Units sold (monthly avg)')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='catalog.attributeoption')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(storage=apps.media.storage.DynamicMediaStorage(), upload_to='product-images/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='attributeoption',
            constraint=models.UniqueConstraint(fields=('attribute', 'value'), name='uniq_attribute_option_value'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', '-revenue_total'], name='idx_status_revenue'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', '-sales_total'], name='idx_status_sales'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', '-sales_per_day'], name='idx_status_sales_day'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', '-updated_at'], name='idx_status_updated'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock'], name='idx_stock'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sales_per_month'], name='idx_sales_month'),
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(fields=('product', 'option'), name='uniq_product_option'),
        ),
    ]
