# Generated by Django 6.0 on 2026-01-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="sort_order",
            field=models.IntegerField(
                default=0,
                help_text="Sort order in navigation menu (lower numbers first).",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                default="circle",
                help_text="Icon name for the menu.",
                max_length=50,
            ),
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["sort_order", "name"], "verbose_name_plural": "Categories"},
        ),
    ]
