# Generated by Django 6.0 on 2026-01-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_historicalattributedefinition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributedefinition',
            name='show_on_tile',
            field=models.BooleanField(default=True, help_text='Whether to display this attribute on product cards/tiles.', verbose_name='Show on product tiles'),
        ),
        migrations.AddField(
            model_name='attributedefinition',
            name='tile_display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which attribute appears on product tiles. Lower numbers appear first.', verbose_name='Tile display order'),
        ),
        migrations.AddField(
            model_name='historicalattributedefinition',
            name='show_on_tile',
            field=models.BooleanField(default=True, help_text='Whether to display this attribute on product cards/tiles.', verbose_name='Show on product tiles'),
        ),
        migrations.AddField(
            model_name='historicalattributedefinition',
            name='tile_display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which attribute appears on product tiles. Lower numbers appear first.', verbose_name='Tile display order'),
        ),
    ]
