# Generated by Django 6.0 on 2026-02-02 10:53

import apps.catalog.models
import apps.media.storage
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_attributedefinition_simplify'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Internal name for identification', max_length=255, verbose_name='Name')),
                ('image', models.ImageField(help_text='Desktop banner. Recommended: 1200x400px. Images scale responsively.', storage=apps.media.storage.DynamicMediaStorage(), upload_to=apps.catalog.models._get_category_banner_filename, verbose_name='Image')),
                ('mobile_image', models.ImageField(blank=True, help_text='Optional mobile banner. Recommended: 800x400px. Falls back to desktop image if not set.', null=True, storage=apps.media.storage.DynamicMediaStorage(), upload_to=apps.catalog.models._get_category_banner_filename, verbose_name='Mobile Image')),
                ('url', models.CharField(blank=True, default='', help_text="URL to redirect when the banner is clicked. Use '#' or relative/full URL.", max_length=500, verbose_name='Target URL')),
                ('is_active', models.BooleanField(default=True, help_text='Only active banners will be displayed', verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower number = higher priority)', verbose_name='Order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='catalog.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category Banner',
                'verbose_name_plural': 'Category Banners',
                'ordering': ['category', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCategoryBanner',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(help_text='Internal name for identification', max_length=255, verbose_name='Name')),
                ('image', models.TextField(help_text='Desktop banner. Recommended: 1200x400px. Images scale responsively.', max_length=100, verbose_name='Image')),
                ('mobile_image', models.TextField(blank=True, help_text='Optional mobile banner. Recommended: 800x400px. Falls back to desktop image if not set.', max_length=100, null=True, verbose_name='Mobile Image')),
                ('url', models.CharField(blank=True, default='', help_text="URL to redirect when the banner is clicked. Use '#' or relative/full URL.", max_length=500, verbose_name='Target URL')),
                ('is_active', models.BooleanField(default=True, help_text='Only active banners will be displayed', verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower number = higher priority)', verbose_name='Order')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.category', verbose_name='Category')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Category Banner',
                'verbose_name_plural': 'historical Category Banners',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCategoryRecommendedProduct',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower number = higher priority)', verbose_name='Order')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.category', verbose_name='Category')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'historical Recommended Product',
                'verbose_name_plural': 'historical Recommended Products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CategoryRecommendedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower number = higher priority)', verbose_name='Order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_products', to='catalog.category', verbose_name='Category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_recommendations', to='catalog.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Recommended Product',
                'verbose_name_plural': 'Recommended Products',
                'ordering': ['category', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('category', 'product'), name='uniq_category_recommended_product')],
            },
        ),
    ]
