# Generated by Django 6.0 on 2026-02-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_category_banners_and_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_banners',
            field=models.BooleanField(default=True, help_text='Display banner slider at the top of the category page.', verbose_name='Show banners'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_recommended_products',
            field=models.BooleanField(default=True, help_text="Display 'Recommended in category' section on the category page.", verbose_name='Show recommended products'),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='show_banners',
            field=models.BooleanField(default=True, help_text='Display banner slider at the top of the category page.', verbose_name='Show banners'),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='show_recommended_products',
            field=models.BooleanField(default=True, help_text="Display 'Recommended in category' section on the category page.", verbose_name='Show recommended products'),
        ),
    ]
