# Generated by Django 6.0 on 2026-02-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_add_category_display_toggles'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorybanner',
            name='tab_title',
            field=models.CharField(blank=True, default='', help_text='Optional title shown in navigation tabs below the banner. Leave empty to hide tabs.', max_length=100, verbose_name='Tab Title'),
        ),
        migrations.AddField(
            model_name='historicalcategorybanner',
            name='tab_title',
            field=models.CharField(blank=True, default='', help_text='Optional title shown in navigation tabs below the banner. Leave empty to hide tabs.', max_length=100, verbose_name='Tab Title'),
        ),
    ]
