# Generated by Django 6.0 on 2026-02-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_add_tab_title_to_category_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='historicalcategory',
            name='sort_order',
        ),
    ]
