# Generated by Django 6.0 on 2026-02-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_category_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden'), ('disabled', 'Disabled')], default='hidden', help_text="Controls product visibility and availability. 'Disabled' products are shown but marked as temporarily unavailable.", max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden'), ('disabled', 'Disabled')], default='hidden', help_text="Controls product visibility and availability. 'Disabled' products are shown but marked as temporarily unavailable.", max_length=20),
        ),
    ]
