# Generated by Django 6.0 on 2026-03-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplugin',
            name='status',
            field=models.CharField(choices=[('activated', 'Activated'), ('deactivated', 'Deactivated')], default='deactivated', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='status',
            field=models.CharField(choices=[('activated', 'Activated'), ('deactivated', 'Deactivated')], default='deactivated', max_length=30, verbose_name='Status'),
        ),
    ]
