# Generated by Django 6.0 on 2026-03-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0002_alter_historicalplugin_status_alter_plugin_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalPluginPackageArtifact",
        ),
        migrations.DeleteModel(
            name="PluginPackageArtifact",
        ),
    ]
